package kz.mybrain.superkassa.presentation.strings.common

/** Қазақ тіліндегі интерфейс мәтіні. */
internal val KazakhStrings = AppStrings(
    common = CommonStrings(
        refresh = "Жаңарту",
        hide = "Жасыру",
        print = "Басып шығару",
        amount = "Сома",
        pin = "ПИН",
        loading = "Оқылуда…",
        starting = "Касса іске қосылуда",
        noAnswer = "Жауап келмеді — құжат өтіп кетуі мүмкін, журналды тексеріңіз; қайталау қосарламайды",
        kassaFailed = "Касса әрекетті орындамады — қайталаңыз; болмаса, қызмет көрсетушіні шақырыңыз",
        refusalCode = "Бас тарту коды",
        deliveredToOfd = "БФД-ға жеткізілді",
        queuedNoLink = "байланыс жоқ — кезекке қойылды",
        deliveryState = "Жеткізу күйі",
        collapse = "Жию",
        explain = "Түсіндірме",
        expand = "Жаю",
        retry = "Қайталау",
        nothingToPick = "Таңдайтын ештеңе жоқ"
    ),
    login = LoginStrings(
        title = "Кассаға кіру",
        search = "Іздеу: нөмір, атауы, ұйым",
        noKkmsTitle = "Бұл жұмыс орнында бірде-бір касса жоқ",
        noKkms = "Мұнда әлі бірде-бір касса тіркелмеген. Касса тіркеңіз немесе кабинеттен бастаңыз.",
        kkmsUnreadTitle = "Кассалар тізімі оқылмады",
        kkmsUnread = "Касса кассалар тізімін бермеді, мұнда қанша касса бары белгісіз. " +
            "Қайталаңыз; болмаса, қызмет көрсетушіні шақырыңыз.",
        yourKkm = "Сіздің кассаңыз",
        pick = "Таңдау",
        picked = "Таңдалды",
        enter = "Кіру",
        reload = "Тізімді жаңарту",
        noKkmChosen = "Касса таңдалмады",
        pickHint = "Тізімнен кассаны таңдаңыз",
        factory = "Зауыттық",
        registrationNumber = "Тіркеу нөмірі"
    ),
    shell = ShellStrings(
        noKkm = "Касса таңдалмады",
        autonomous = "Дербес режим",
        blocked = "Бұғатталған",
        changeCashier = "Кассирді ауыстыру",
        moreActions = "Тағы"
    ),
    sections = SectionStrings(
        dashboard = "Басты бет",
        sale = "Сату",
        returns = "Қайтару",
        cash = "Ақша",
        history = "Тарих",
        queue = "Кезек",
        users = "Кассирлер",
        settings = "Баптаулар",
        register = "Жаңа касса",
        cabinet = "БФД кабинеті"
    ),
    dashboard = DashboardStrings(
        state = "Күйі",
        shift = "Ауысым",
        shiftOpenNo = "№ %s ашық",
        shiftClosed = "Жабық",
        documentsInShift = "Ауысымдағы құжаттар",
        shiftDocuments = "Ауысым құжаттары",
        refused = "БФД қабылдамады",
        refusedHint = "Бұл құжаттарды БФД қабылдамады: олар фискалдық болмады, ауысым есептеуішіне кірмеді " +
            "және баспа түрі жоқ. Бас тарту коды мен кассир қызмет көрсетуге қажет.",
        openShift = "Ауысымды ашу",
        xReport = "X-есеп",
        closeShift = "Ауысымды жабу",
        closeShiftAsk = "Ауысымды жабып, Z-есеп алу керек пе?",
        closeShiftExplain = "Ауысымдағы құжат: %s, жәшікте %s. Z-есеп БФД-ға кетеді, ауысым қайтарылмайды.",
        closeShiftCashout = "Қалған қолма-қол ақша есеппен бірге алынады.",
        closeShiftKeepsCash = "Қалған қолма-қол ақша жәшікте қалып, жаңа ауысымға көшеді.",
        shiftTooLong = "Ауысым тәуліктен ұзақ ашық — оны Z-есеппен жабыңыз, әйтпесе БФД кассаны бұғаттайды.",
        shiftDayLimit = "Ауысымды %s дейін жабыңыз: одан кейін касса чекке, қайтаруға және ақшаға бас тартады.",
        openShiftHint = "Ауысым жабық — чек басу үшін ауысымды ашыңыз",
        openShiftAdmin = "Ауысымды әкімші ашады — күнді бастау үшін оны шақырыңыз.",
        shiftOpened = "Ауысым ашылды",
        shiftClosedDone = "Ауысым жабылды, Z-есеп жіберілді",
        xReportDone = "X-есеп жасалды",
        printForm = "Басып шығару пішіні",
        shiftUnknown = "Белгісіз",
        shiftEmpty = "Әзірге құжат жоқ",
        shiftEmptyHint = "Ауысым ашық: бірінші чек өткізілген бойда осында шығады.",
        documentsUnread = "Ауысым құжаттарын оқу мүмкін болмады",
        documentsUnreadHint = "Ауысым ашық, бірақ касса оның құжаттарын берген жоқ: саны белгісіз.",
        shiftUnknownHint = "Касса ауысым күйін айтпады — кассаны қайта оқыңыз; " +
            "көмектеспесе, қызмет көрсетушіні шақырыңыз.",
        documentNo = "№"

    ),
    autonomous = AutonomousStrings(
        title = "Дербес режим",
        explain = "БФД-мен байланыс жоқ. Чектер басылып, дербес белгі алады, " +
            "ал байланыс пайда болған бойда БФД-ға өздері жіберіледі. Жұмысты жалғастыруға болады.",
        waiting = "Жіберуді күтуде",
        checkLink = "Байланысты тексеру",
        sendQueued = "Жиналғанды жіберу",
        sendQueuedRules = "Жинақталғанды әкімші жібереді: ауысым жабық болуы және касса бағдарламалау режимінде болуы керек.",
        linkBack = "БФД-мен байланыс қалпына келді"
    ),
    sale = SaleStrings(
        receipt = "Чек",
        sale = "Сату",
        purchase = "Сатып алу",
        issueSale = "Чекті басу",
        issuePurchase = "Сатып алуды ресімдеу",
        issuing = "Ресімделуде…",
        name = "Атауы",
        price = "Бағасы",
        quantity = "Саны",
        measureUnit = "Өлшем бірлігі",
        vat = "ҚҚС",
        discount = "Жеңілдік",
        storno = "Сторно",
        stornoUndo = "Сторноны алып тастау",
        add = "Қосу",
        remove = "Алып тастау",
        clearBasket = "Себетті тазалау",
        receiptDiscount = "Чекке жеңілдік",
        receiptMarkup = "Чекке үстеме",
        discountOrMarkup = "Чекке жеңілдік пен үстеме — біреуі ғана",
        customerBin = "Сатып алушының ЖСН/БСН",
        taken = "Қабылданды",
        total = "Барлығы",
        barcode = "Штрих-код",
        barcodeSearch = "Штрих-код бойынша іздеу",
        barcodeSearching = "Ізделуде…",
        barcodeFind = "Табу",
        barcodeMissing = "Анықтамалықта мұндай штрих-код жоқ — позицияны қолмен қосыңыз.",
        barcodeUnavailable = "Анықтамалық қазір қолжетімсіз — позицияны қолмен қосыңыз.",
        payment = "Төлем түрі",
        delivered = "чек басылды және БФД-ға жеткізілді",
        queued = "чек басылды, байланыс жоқ — кезекке қойылды"
    ),
    returns = ReturnStrings(
        title = "Қайтару",
        empty = "Ағымдағы ауысымда қайтаруға негіз болатын чек жоқ.",
        receiptNo = "Чек №",
        refundFor = "№ чек бойынша қайтару",
        saleReturn = "Сатуды қайтару",
        giveBack = "Сатып алушыға қайтару",
        purchaseReturn = "Сатып алуды қайтару",
        takeBack = "Кері қабылдау",
        done = "ресімделді, күйі"
    ),
    cash = CashStrings(
        deposit = "Салу",
        withdraw = "Алу",
        deposited = "Салынды",
        withdrawn = "Алынды"
    ),
    queue = QueueStrings(
        title = "Жіберу кезегі",
        empty = "Күтіп тұрған құжат жоқ — бәрі БФД-ға жеткізілді.",
        waiting = "Жіберуді күтуде",
        attempts = "Әрекеттер",
        retryFailed = "Сәтсіздерді қайталау",
        retryDone = "Сәтсіз тапсырмалар қайталауға қойылды"
    ),
    users = UserStrings(
        title = "Кассирлер мен пиндер",
        name = "Аты",
        create = "Тіркеу",
        created = "тіркелді",
        newPin = "Жаңа пин",
        change = "Ауыстыру",
        changed = "Пин ауыстырылды",
        delete = "Жою",
        deleted = "жойылды",
        role = "Рөлі",
        admin = "Әкімші",
        cashier = "Кассир"
    ),
    settings = kazakhSettings,
    preview = kazakhPreview,
    status = kazakhStatus,
    enums = kazakhEnums
)
