package kz.mybrain.superkassa.desktop.ui.strings

/** Надписи кабинета по-английски. Состав полей задан в [CabinetTexts]. */
internal val cabinetTextsEn = CabinetTexts(
    title = "OFD cabinet",
    signIn = "Sign in with a certificate",
    signInHint = "NCALayer asks for the signature: certificate and password are entered in its own window",
    signing = "Waiting for the signature in NCALayer",
    signOut = "Sign out",
    noNcaLayer = "NCALayer does not answer. Start it and sign in again",
    signDeclined = "No signature received",
    signWindowClosed = "The signing window was closed",
    sessionExpired = "Access expired — sign in again",
    unreachable = "The cabinet does not answer at the configured address",
    address = "Cabinet address",
    addressHint = "The cabinet is a separate service with its own address",
    company = "Company",
    bin = "BIN",
    okeds = "Activity codes",
    okedsEmpty = "No activity codes set",
    primaryOked = "Primary",
    saveOkeds = "Save activity codes",
    places = "Retail places",
    placesEmpty = "No retail places yet — add the first one",
    addPlace = "Create a retail place",
    placeName = "Place name",
    placeAddress = "Address",
    findAddress = "Find an address",
    registerCount = "Registers",
    registers = "Cash registers",
    registersEmpty = "No cash registers yet — add the first one",
    addRegister = "Create a register",
    factoryNumber = "Factory number",
    manufactureYear = "Year of manufacture",
    model = "Model",
    modelNotFound = "Model not found",
    internalName = "Register name",
    status = "Status",
    registrationNumber = "Registration number",
    technicalState = "Technical state",
    shift = "Shift",
    lastContact = "Last contact",
    issueToken = "Issue a token",
    tokenIssued = "Token issued",
    registration = "Register",
    reregistration = "Re-register",
    deregistration = "Deregister",
    actionsEmpty = "No registration actions yet",
    reason = "Reason",
    comment = "Comment",
    newPlace = "New retail place",
    card = "Registration card",
    cardMissing = "No registration card",
    savePdf = "Save PDF",
    cardVersions = "Card versions",
    cardVersionsEmpty = "No earlier card versions",
    cardVersionsEmptyHint = "A version appears on re-registration and on deregistration",
    cardVersion = "Version",
    cardCurrentVersion = "Current",
    cardChanged = "Changed",
    documents = "Documents",
    receipts = "Receipts",
    shifts = "Shifts",
    reports = "Reports",
    cashMovements = "Cash movements",
    documentsEmpty = "No documents",
    chooseRegister = "Choose a register",
    refresh = "Refresh",
    add = "Add",
    remove = "Remove",
    save = "Save",
    reasonCessation = "No longer in use",
    reasonBroken = "Out of order",
    reasonLost = "Lost",
    reasonOther = "Other",
    iin = "IIN",
    place = "Retail place",
    makePrimary = "Make primary",
    latitude = "Latitude",
    longitude = "Longitude",
    rename = "Rename",
    changeAddress = "Change the address",
    deleteRegister = "Delete the register",
    deleteOnlyDraft = "Only a register that is not on record yet can be deleted",
    statusDraft = "Draft",
    statusRegistered = "On record",
    statusDeregistered = "Deregistered",
    statusActive = "Working",
    statusInactive = "Stopped",
    statusAccepted = "Accepted",
    statusRejected = "Refused",
    statusSent = "Sent",
    statusInProcess = "The KGD is reviewing",
    shiftOpen = "Shift is open",
    shiftClosed = "Shift is closed",
    operationSale = "Sale",
    operationReturn = "Sale return",
    operationPurchase = "Purchase",
    operationPurchaseReturn = "Purchase return",
    reportZ = "Z report",
    reportX = "X report",
    deposit = "Cash in",
    withdrawal = "Cash out",
    delivered = "Delivered",
    pending = "Queued",
    kgdMarked = "KGD mark",
    receiptItems = "Items",
    receiptPayments = "Payment",
    receiptTaxes = "Taxes",
    receiptTotal = "Total",
    operator = "Cashier",
    close = "Close",
    companyFromEds = "The company here is the one whose digital signature you signed " +
        "in with: the name and the details are issued by the KGD and are not editable. " +
        "Retail places, registers and applications all belong to it",
    placesEmptyHint = "A place is the address where a register stands. Until there is one, no register can be added",
    registersEmptyHint = "Create a register, then file a KGD application to put it on record",
    okedsEmptyHint = "The primary activity code goes into the registration application — set at least one",
    chooseRegisterHint = "The company registers are on the left: choose one and its card opens here",
    documentsEmptyHint = "Whatever the OFD accepted from this register appears here",
    actionsEmptyHint = "Every application leaves a trace here: when it was filed and how it ended",
    pickRegisterFirst = "No register chosen",
    pickRegisterFirstHint = "Choose a register above: documents are shown one register at a time",
    technicalUnknown = "The data reception server has not seen this register yet",
    technicalUnknownHint = "The state appears after the register first contacts the OFD",
    trafficSuspended = "Document reception is suspended",
    ofdDisconnected = "The link to the OFD is broken",
    passport = "Register passport",
    applications = "KGD applications",
    actionsJournal = "Action journal",
    token = "Token",
    tokenHint = "The key the register signs its requests with. Copy it into the register settings: it is not shown here twice",
    submitApplication = "File the application",
    applicationSent = "Application sent",
    registerStatus = "Register status",
    applicationWait = "The KGD answers later — the journal below refreshes itself",
    required = "Required",
    optional = "Optional",
    internalNameHint = "A note to yourself: it is not sent to the OFD",
    foundAddresses = "Addresses found",
    addressChosen = "Address chosen",
    addOked = "Add an activity code",
    placeRemoveBlocked = "A place with registers cannot be removed",
    receiptMoment = "Issued at",
    kkmDocumentNumber = "Cash register document number",
    noKgdMark = "No KGD mark",
    documentDataMissing = "The cabinet returned no document data: there is nothing to draw",
    receiptTaken = "Taken",
    receiptChange = "Change",
    receiptDiscount = "Discount",
    receiptMarkup = "Markup",
    paymentCash = "Cash",
    paymentCard = "Card",
    paymentElectronic = "Electronic",
    paymentMobile = "Mobile payment",
    paymentCredit = "On credit",
    paymentTare = "Returnable packaging",
    taxVat = "VAT",
    receiptsHint = "Click a row to open the receipt contents",
    deliveryRefused = "Not delivered",
    cardMissingHint = "The card appears once the register is put on record",
    factoryLocked = "Recorded in the registration card — changed only by re-registration",
    factoryIssued = "Assigned by the register when issued — not editable",
    tokenOnlyRegistered = "A token is issued to a register on record, and only when no application is filed for it",
    kkmNotActive = "The register is not admitted to service at the acceptance server",
    defaultPinNotAllowed = "The register still has the default PIN — change it on the register itself",
    missing = "Not filled in",
    periodToday = "Today",
    periodWeek = "Week",
    periodMonth = "Month",
    periodAll = "All",
    showMore = "Show more",
    allShown = "The whole period is shown",
    shownOf = "Shown %1\$s of %2\$s",
    okedSearch = "Search the OKED classifier",
    okedSearchHint = "A code or part of a name; an empty line shows the start of the classifier",
    okedNotFound = "Nothing found. The classifier knows only its own wording: a pharmacy there is trade in pharmaceutical goods",
    shiftOpenTitle = "The shift is open",
    shiftOpenAsk = "A register can be taken off record only with the shift closed. Close the shift on this register and file the application?",
    shiftOpenElsewhere = "The shift is open and the register is set up on another machine — close the shift there",
    closeShiftAndDeregister = "Close the shift and take off record",
    adminPin = "Administrator PIN",
    stateDisagree = "They disagree",
    sourceNode = "Node",
    sourceCabinet = "Cabinet",
    sourceOfd = "OFD",
    inWork = "In work",
    verdictYes = "Yes",
    verdictNo = "No",
    verdictUnknown = "Unknown",
    okedNarrowSearch = "The classifier is longer than shown: “Show more” at the end of the list, or narrow the search",
    pickOnMap = "Place on the map",
    pointNotChosen = "No point chosen",
    noApplications = "The register is off the record — no applications are filed for it",
    applicationInFlight = "An application is already filed — the next one after the KGD reply",
    openedAt = "Opened",
    closedAt = "Closed",
    revenue = "Revenue",
    cashInDrawer = "Cash in drawer",
    sales = "Sales",
    returns = "Returns",
    autonomous = "Issued offline",
    documentMoment = "Accepted by OFD",
    documentNumber = "Document number",
    developerSignIn = "Sign in without a digital signature",
    developerSignInHint = "Cabinet development mode: the owner and company are set by IIN and BIN, " +
        "the signature is not checked at sign-in. Applications are still signed with the digital signature, " +
        "and the IIN must match the certificate; for a sole proprietor the BIN equals the IIN",
    addressRegion = "Region",
    addressLocality = "Locality or district",
    addressStreet = "Street",
    addressBuilding = "Building number",
    addressStepHint = "The address is chosen step by step: region, locality, street, building. " +
        "Pick from the list or type the beginning of a name as the registry spells it: " +
        "Қабанбай батыр, not Кабанбай",
    okedCode = "OKED code",
    okedName = "Activity name",
    okedManualHint = "The cabinet does not serve the classifier: " +
        "enter the code and the name exactly as written in the OKED classifier",
    stagePreparing = "Preparing the application",
    stageSigning = "Waiting for the signature in NCALayer",
    stageSending = "Sending to the cabinet",
    applicationFailed = "The application was not sent",
    addressPickAgain = "Pick another address",
    addressNotFound = "Nothing found — refine the beginning of the name",
    placeSearch = "Search: place, register, reg. no.",
    placeNotFound = "Nothing found",
    placeNotFoundHint = "Change the query or clear the search.",
    registersHint = "Every cash register created in the cabinet, not only the ones " +
        "running on this machine. A register is created here first, then filed for the " +
        "record, and the KGD assigns it a registration number",
    placesHint = "A retail place is the address where a register stands: it goes into the " +
        "KGD application and is printed on the receipt. The coordinates are for the map — " +
        "they show where the place is and where its registers connect from",
    placesTreeHint = "The retail places of the company on the left, each with its " +
        "registers under it: a register lives in a place, and without a place it cannot " +
        "be created. The search covers the place name, the register name and its number",
    okedsHint = "The activity types are what the company does, taken from the OKED " +
        "classifier (NC RK 03-2019); the cabinet holds the classifier, so a type is " +
        "picked from the list rather than typed in your own words. There is exactly one " +
        "primary type: it goes into the application, and without it the KGD will not put " +
        "a register on record",
    passportHint = "The passport is how the register is recorded at the KGD: registration " +
        "number, factory number, model and retail place. It also shows whether this " +
        "register runs on this machine, and lets you edit what can still be edited",
    onThisMachineHint = "The registers in the cabinet and the registers on this computer " +
        "are different lists: a register can be on record and still run in another shop. " +
        "This says whether a cashier can stand behind it here and now",
    receiptCardHint = "The receipt in full: items, payment, taxes and who rang it up. The " +
        "KGD mark is what the receipt is opened for: it means the receipt reached the BFD " +
        "and was accepted",
    reportCardHint = "The register report for a shift: revenue, refunds and the cash in " +
        "the drawer. The numbers must match the tape the cashier holds — a mismatch means " +
        "not everything reached the BFD",
    shiftCardHint = "A shift is one register's working day, from opening to the Z report. " +
        "The totals appear after it closes: an open shift has none yet, and the empty " +
        "lines here are not a fault",
    cashMovementHint = "A deposit or a withdrawal is money the cashier put into the " +
        "drawer or took out of it without selling anything. It is not revenue, but it " +
        "changes the cash in the register, and without it the drawer will not reconcile",
    factoryNumberHint = "The number the manufacturer stamped on the register: it goes " +
        "into the application and stands in the registration card. While the register " +
        "is not on record it can be fixed here",
    map = MapTexts(
        pickOnMapHint = "Click the map where the place stands; drag the map with the mouse",
        pickPoint = "Take these coordinates",
        zoomIn = "Zoom in",
        zoomOut = "Zoom out",
        myLocation = "Show my city",
        myLocationShown = "The blue dot is your city by connection address",
        myLocationPrecise = "The blue dot is where you are, by this machine location service",
        findHouse = "Street address",
        locationAsk = "Detect the location?",
        locationAskHint = "The application will ask an external service which city your " +
            "connection address belongs to. Only the address itself leaves the machine — " +
            "neither the register nor the company is named. The accuracy is a city, not " +
            "a building: place the point itself by clicking the map.",
        locationAllow = "Allow",
        locationDeny = "Do not allow"
    )
)
