package kz.mybrain.superkassa.desktop.ui.strings

/** Надписи кабинета по-английски. Состав полей задан в [CabinetTexts]. */
internal val cabinetTextsEn = CabinetTexts(
    title = "BFD cabinet",
    signIn = "Sign in with a certificate",
    signing = "Waiting for the signature in NCALayer",
    signOut = "Sign out",
    noNcaLayer = "NCALayer does not answer. Start it and sign in again",
    signDeclined = "No signature received",
    signWindowClosed = "The signing window was closed",
    signCancelled = "Signing was cancelled in NCALayer",
    sessionExpired = "Access expired — sign in again",
    unreachable = "The cabinet does not answer at the configured address",
    address = "Cabinet address",
    company = "Company",
    bin = "BIN",
    okeds = "Activity codes",
    okedsEmpty = "No activity codes set",
    primaryOked = "Primary",
    saveOkeds = "Save activity codes",
    places = "Retail places",
    placesEmpty = "No retail places yet — add the first one",
    addPlace = "Create a retail place",
    placeName = "Place name",
    placeAddress = "Address",
    findAddress = "Find an address",
    registerCount = "Registers",
    registers = "Cash registers",
    registersEmpty = "No cash registers yet — add the first one",
    addRegister = "Create a register",
    factoryNumber = "Factory number",
    manufactureYear = "Year of manufacture",
    model = "Model",
    modelNotFound = "Model not found",
    internalName = "Register name",
    status = "Status",
    registrationNumber = "Registration number",
    technicalState = "Technical state",
    shift = "Shift",
    lastContact = "Last contact",
    issueToken = "Issue a token",
    tokenIssued = "Token issued",
    tokenGoesToNode = "The new token has been written into the register on this machine",
    localInfoSynced = "The register details on this machine have been refreshed",
    localInfoNeedsSync = "The new place reaches receipts after the details are synced in the register settings: it cannot be done right now",
    tokenNeedsNode = "The register works on this machine: write the new token into its settings, otherwise it stops at the first receipt",
    registration = "Register",
    reregistration = "Re-register",
    deregistration = "Deregister",
    actionsEmpty = "No registration actions yet",
    reason = "Reason",
    comment = "Comment",
    newPlace = "New retail place",
    card = "Registration card",
    cardMissing = "No registration card",
    savePdf = "Save PDF",
    cardVersions = "Card versions",
    cardVersionsEmpty = "No earlier card versions",
    cardVersion = "Version",
    cardCurrentVersion = "Current",
    cardChanged = "Changed",
    documents = "Documents",
    receipts = "Receipts",
    shifts = "Shifts",
    reports = "Reports",
    cashMovements = "Cash movements",
    documentsEmpty = "No documents",
    documentsNoneInPeriod = "No documents for this period",
    chooseRegister = "Choose a register",
    refresh = "Refresh",
    add = "Add",
    remove = "Remove",
    save = "Save",
    reasonCessation = "Not in use",
    reasonBroken = "Out of order",
    reasonLost = "Lost",
    reasonOther = "Other",
    iin = "IIN",
    place = "Retail place",
    makePrimary = "Make primary",
    latitude = "Latitude",
    longitude = "Longitude",
    rename = "Rename",
    changeAddress = "Change the address",
    deleteRegister = "Delete the register",
    deleteOnlyDraft = "Only a register that is not on record yet can be deleted",
    statuses = CabinetStatusNames(
        draft = "Draft",
        registered = "On record",
        deregistered = "Deregistered",
        active = "Working",
        inactive = "Stopped",
        blocked = "Blocked",
        accepted = "Accepted",
        rejected = "Refused",
        sent = "Sent",
        inProcess = "The KGD is reviewing",
        shiftOpen = "Shift is open",
        shiftClosed = "Shift is closed",
        unknown = "State is unknown"
    ),
    operationSale = "Sale",
    operationReturn = "Sale return",
    operationPurchase = "Purchase",
    operationPurchaseReturn = "Purchase return",
    reportZ = "Z report",
    reportX = "X report",
    deposit = "Cash in",
    withdrawal = "Cash out",
    delivered = "Delivered",
    pending = "Queued",
    kgdMarked = "KGD mark",
    receiptItems = "Items",
    receiptPayments = "Payment",
    receiptTaxes = "Taxes",
    receiptTotal = "Total",
    operator = "Cashier",
    close = "Close",
    companyFromEds = "The company here is the one whose digital signature you signed " +
        "in with: the name and the details are issued by the KGD and are not editable. " +
        "Retail places, registers and applications all belong to it",
    pickRegisterFirst = "No register chosen",
    technicalUnknown = "The BFD has not seen this register yet",
    trafficSuspended = "Document reception is suspended",
    bfdDisconnected = "The link to the BFD is broken",
    passport = "Register passport",
    applications = "KGD applications",
    actionsJournal = "Action journal",
    token = "Token",
    submitApplication = "File the application",
    applicationSent = "Application sent",
    registerStatus = "Register status",
    applicationWait = "The KGD answers later — the journal below refreshes itself",
    required = "Required",
    optional = "Optional",
    foundAddresses = "Addresses found",
    addressChosen = "Address chosen",
    addressChanged = "The address has been changed",
    addressNeedsReregistration = "The address is unchanged: re-register the cash registers of this place first",
    addOked = "Add an activity code",
    placeRemoveBlocked = "A place with registers cannot be removed",
    receiptMoment = "Issued at",
    kkmDocumentNumber = "Cash register document number",
    noKgdMark = "not received",
    documentDataMissing = "The cabinet returned no document data: there is nothing to draw",
    receiptTaken = "Taken",
    receiptChange = "Change",
    receiptDiscount = "Discount",
    receiptMarkup = "Markup",
    paymentCash = "Cash",
    paymentCard = "Card",
    paymentElectronic = "Electronic",
    paymentMobile = "Mobile payment",
    paymentCredit = "On credit",
    paymentTare = "Returnable packaging",
    taxVat = "VAT",
    deliveryRefused = "Not delivered",
    factoryLocked = "Recorded in the registration card — changed only by re-registration",
    factoryIssued = "Assigned by the register when issued — not editable",
    tokenOnlyRegistered = "A token is issued to a register on record, and only when no application is filed for it",
    kkmNotActive = "The register is not admitted to service at the acceptance server",
    defaultPinNotAllowed = "The register still has the default PIN — change it on the register itself",
    missing = "Not filled in",
    periodToday = "Today",
    periodWeek = "Week",
    periodMonth = "Month",
    periodAll = "All",
    showMore = "Show more",
    allShown = "The whole period is shown",
    shownOf = "Shown %1\$s of %2\$s",
    okedSearch = "Search the OKED classifier",
    okedNotFound = "Nothing found. The classifier knows only its own wording: a pharmacy there is trade in pharmaceutical goods",
    shiftOpenTitle = "The shift is open",
    shiftOpenAsk = "A register can be taken off record only with the shift closed. Close the shift on this register and file the application?",
    shiftOpenElsewhere = "The shift is open and the register is set up on another machine — close the shift there",
    closeShiftAndDeregister = "Close the shift and take off record",
    adminPin = "Administrator PIN",
    stateDisagree = "They disagree",
    stateDisagreeNote = "They disagree: %s. Most likely the state went stale somewhere — reread the register " +
        "card; if the disagreement stays, work out who is right",
    sourceNode = "Node",
    sourceCabinet = "Cabinet",
    sourceBfd = "BFD",
    stateWorking = "The register is in service",
    stateBlocked = "The register is blocked",
    stateOffRecord = "The register is off record",
    stateWorkUnknown = "Nobody said whether the register works",
    stateShiftUnknown = "Nobody knows whether the shift is open",
    claimWorking = "the register is in service",
    claimBlocked = "the register is blocked",
    claimOnRecord = "the register is on record",
    claimOffRecord = "the register is off record",
    claimRecordUnread = "the record was not read",
    claimNotFiled = "never filed for record",
    claimIsnaPending = "KGD is reviewing the application",
    claimIsnaRefused = "KGD refused the record",
    claimNodeNoKkm = "does not know this register",
    claimBfdNoKkm = "has not seen the register yet",
    claimBfdNoAnswer = "did not answer about the register",
    claimShiftOpen = "the shift is open",
    claimShiftClosed = "the shift is closed",
    claimShiftNotKept = "does not keep shifts",
    shiftNumberTitle = "Shift number",
    shiftNumberNone = "there have been no shifts yet",
    lastContactNever = "the register has never made contact",
    okedNarrowSearch = "The classifier is longer than shown: “Show more” at the end of the list, or narrow the search",
    pickOnMap = "Place on the map",
    pointNotChosen = "No point chosen",
    noApplications = "The register is off the record — no applications are filed for it",
    applicationInFlight = "An application is already filed — the next one after the KGD reply",
    openedAt = "Opened",
    closedAt = "Closed",
    revenue = "Revenue",
    cashInDrawer = "Cash in drawer",
    sales = "Sales",
    returns = "Returns",
    autonomous = "Issued offline",
    documentMoment = "Accepted by BFD",
    documentNumber = "Document number",
    addressRegion = "Region",
    addressLocality = "Locality or district",
    addressStreet = "Street",
    addressBuilding = "Building number",
    okedCode = "OKED code",
    okedName = "Activity name",
    stagePreparing = "Preparing the application",
    stageSigning = "Waiting for the signature in NCALayer",
    stageSending = "Sending to the cabinet",
    applicationFailed = "The application was not sent",
    addressPickAgain = "Pick another address",
    addressNotFound = "The registry returned nothing for this step — refine the query or retry later",
    placeSearch = "Search: place, register, KGD number",
    placeNotFound = "Nothing found",
    map = MapTexts(
        pickOnMapHint = "Click the map where the place stands; drag the map with the mouse",
        pickPoint = "Take these coordinates",
        noTiles = "No map imagery: the tile service did not answer. The place is still set by clicking",
        showDegrees = "Find on the map",
        zoomIn = "Zoom in",
        zoomOut = "Zoom out",
        myLocation = "Show my city",
        myLocationShown = "The haloed dot is your city by connection address",
        myLocationPrecise = "The haloed dot is where you are, by this machine location service",
        findHouse = "Street address",
        locationAsk = "Detect the location?",
        locationAskHint = "The application will ask an external service which city your " +
            "connection address belongs to. Only the address itself leaves the machine — " +
            "neither the register nor the company is named. The accuracy is a city, not " +
            "a building: place the point itself by clicking the map.",
        locationAllow = "Allow",
        locationDeny = "Do not allow"
    ),
    hints = CabinetHints(
        signIn = "NCALayer asks for the signature: certificate and password are entered in its own window",
        signWait = "NCALayer opens the signing window. It may have appeared behind the main window — " +
            "look for it among the windows. If there is none, stop waiting and sign in again",
        signNoAnswer = "NCALayer accepted the request but returned no signature: it is busy or never showed " +
            "the signing window. Check the NCALayer windows and sign in again",
        address = "The cabinet is a separate service with its own address",
        cardVersionsEmpty = "A version appears on re-registration and on deregistration",
        placesEmpty = "A place is the address where a register stands. Until there is one, no register can be added",
        registersEmpty = "Create a register, then file a KGD application to put it on record",
        okedsEmpty = "The primary activity code goes into the registration application — set at least one",
        chooseRegister = "The company registers are on the left: choose one and its card opens here",
        documentsEmpty = "Whatever the BFD accepted from this register appears here",
        documentsNoneInPeriod = "The register has documents from another time — widen the period or take the whole time",
        actionsEmpty = "Every application leaves a trace here: when it was filed and how it ended",
        pickRegisterFirst = "Places and their registers are on the left: pick one and it opens here",
        technicalUnknown = "The state appears after the register first contacts the BFD",
        token = "The key the register signs its requests with. Copy it into the register settings: it is not shown here twice",
        internalName = "A note to yourself: it is not sent to the BFD",
        receipts = "Click a row to open the receipt contents",
        cardMissing = "The card appears once the register is put on record",
        okedSearch = "A code or part of a name; an empty line shows the start of the classifier",
        technicalState = "Three parties speak about the register: the node on this machine, the KGD cabinet and " +
            "the BFD — the fiscal data base. The answer comes first, and below it who exactly said so. They " +
            "disagree when the state went stale somewhere.",
        bfdNoAnswer = "The state was not received — reread the register card",
        addressStep = "The address is chosen step by step: region, locality, street, building. " +
            "Pick from the list or type the beginning of a name as the registry spells it: " +
            "Қабанбай батыр, not Кабанбай",
        okedManual = "The cabinet does not serve the classifier: " +
            "enter the code and the name exactly as written in the OKED classifier",
        placeNotFound = "Change the query or clear the search",
        registers = "Every cash register created in the cabinet, not only the ones " +
            "running on this machine. A register is created here first, then filed for the " +
            "record, and the KGD assigns it a registration number",
        places = "A retail place is the address where a register stands: it goes into the " +
            "KGD application and is printed on the receipt. The coordinates are for the map — " +
            "they show where the place is and where its registers connect from",
        placesTree = "The retail places of the company on the left, each with its " +
            "registers under it: a register lives in a place, and without a place it cannot " +
            "be created. The search covers the place name, the register name and its number",
        okeds = "The activity types are what the company does, taken from the OKED " +
            "classifier (NC RK 03-2019); the cabinet holds the classifier, so a type is " +
            "picked from the list rather than typed in your own words. There is exactly one " +
            "primary type: it goes into the application, and without it the KGD will not put " +
            "a register on record",
        passport = "The passport is how the register is recorded at the KGD: registration " +
            "number, factory number, model and retail place. It also shows whether this " +
            "register runs on this machine, and lets you edit what can still be edited",
        onThisMachine = "The registers in the cabinet and the registers on this computer " +
            "are different lists: a register can be on record and still run in another shop. " +
            "This says whether a cashier can stand behind it here and now",
        receiptCard = "The receipt in full: items, payment, taxes and who rang it up. The " +
            "KGD mark is what the receipt is opened for: it means the receipt reached the BFD " +
            "and was accepted",
        reportCard = "The register report for a shift: revenue, refunds and the cash in " +
            "the drawer. The numbers must match the tape the cashier holds — a mismatch means " +
            "not everything reached the BFD",
        shiftCard = "A shift is one register's working day, from opening to the Z report. " +
            "The totals appear after it closes: an open shift has none yet, and the empty " +
            "lines here are not a fault",
        cashMovement = "A deposit or a withdrawal is money the cashier put into the " +
            "drawer or took out of it without selling anything. It is not revenue, but it " +
            "changes the cash in the register, and without it the drawer will not reconcile",
        factoryNumber = "The number the manufacturer stamped on the register: it goes " +
            "into the application and stands in the registration card. While the register " +
            "is not on record it can be fixed here",
        card = "The registration card is what the KGD recorded about the register: " +
            "number, model, retail place and the date it went on record. A new card version " +
            "appears with every re-registration, and the versions show what exactly changed",
        actionsJournal = "The trail of every application to the KGD: which one was filed, " +
            "when, and how it ended. This is where you look to see why the register is in " +
            "its current state, or to prove that an application was filed",
        newPlaceNotChosen = "Re-registration moves the register to another retail place — " +
            "choose it in the list above, otherwise the cabinet will refuse the application"
    )
)
