package kz.mybrain.superkassa.desktop.ui.strings

/**
 * Надписи выбора тона, шрифта и размера в карточке «Оформление».
 *
 * Свой набор внутри настроек: карточка одна, а надписей у неё три
 * десятка, и в общем перечне настроек они заслонили бы всё остальное.
 */
data class LookStrings(
    val accent: String,
    val accentHint: String,
    val accentRed: String,
    val accentOrange: String,
    val accentAmber: String,
    val accentOlive: String,
    val accentLime: String,
    val accentGreen: String,
    val accentEmerald: String,
    val accentTeal: String,
    val accentAzure: String,
    val accentBlue: String,
    val accentIndigo: String,
    val accentViolet: String,
    val accentLilac: String,
    val accentPink: String,
    val typeface: String,
    val typefaceSystem: String,
    val typefaceSans: String,
    val typefaceSerif: String,
    val typefaceMono: String,
    val textScale: String,
    val textScaleHint: String,
    val textScaleDense: String,
    val textScaleCompact: String,
    val textScaleNormal: String,
    val textScaleLarge: String,
    val textScaleLarger: String
)

internal val russianLook = LookStrings(
    accent = "Тон",
    accentHint = "Основной цвет кнопок, выделения и значков. Отказ остаётся красным при любом тоне.",
    accentRed = "Красный",
    accentOrange = "Оранжевый",
    accentAmber = "Янтарный",
    accentOlive = "Оливковый",
    accentLime = "Лаймовый",
    accentGreen = "Зелёный",
    accentEmerald = "Изумрудный",
    accentTeal = "Бирюзовый",
    accentAzure = "Лазурный",
    accentBlue = "Синий",
    accentIndigo = "Индиго",
    accentViolet = "Фиолетовый",
    accentLilac = "Сиреневый",
    accentPink = "Розовый",
    typeface = "Шрифт",
    typefaceSystem = "Системный",
    typefaceSans = "Без засечек",
    typefaceSerif = "С засечками",
    typefaceMono = "Моноширинный",
    textScale = "Размер",
    textScaleHint = "Плотный — для товарного списка, крупные — для кассового стола: с них итог читается с метра.",
    textScaleDense = "Плотный",
    textScaleCompact = "Компактный",
    textScaleNormal = "Обычный",
    textScaleLarge = "Крупный",
    textScaleLarger = "Крупнее"
)

internal val kazakhLook = LookStrings(
    accent = "Реңк",
    accentHint = "Түймелердің, ерекшелеудің және белгішелердің негізгі түсі. " +
        "Бас тарту кез келген реңкте қызыл болып қалады.",
    accentRed = "Қызыл",
    accentOrange = "Қызғылт сары",
    accentAmber = "Кәріптас",
    accentOlive = "Зәйтүн",
    accentLime = "Лайм",
    accentGreen = "Жасыл",
    accentEmerald = "Зүмірет",
    accentTeal = "Көгілдір",
    accentAzure = "Ашық көк",
    accentBlue = "Көк",
    accentIndigo = "Индиго",
    accentViolet = "Күлгін",
    accentLilac = "Сирень",
    accentPink = "Қызғылт",
    typeface = "Қаріп",
    typefaceSystem = "Жүйелік",
    typefaceSans = "Кертіксіз",
    typefaceSerif = "Кертікті",
    typefaceMono = "Бір енді",
    textScale = "Өлшем",
    textScaleHint = "Тығыз — тауар тізіміне, ірілері — касса үстеліне: олармен қорытынды бір метрден оқылады.",
    textScaleDense = "Тығыз",
    textScaleCompact = "Ықшам",
    textScaleNormal = "Қалыпты",
    textScaleLarge = "Үлкен",
    textScaleLarger = "Ірірек"
)

internal val englishLook = LookStrings(
    accent = "Accent",
    accentHint = "Main colour of buttons, selection and icons. Refusal stays red with any accent.",
    accentRed = "Red",
    accentOrange = "Orange",
    accentAmber = "Amber",
    accentOlive = "Olive",
    accentLime = "Lime",
    accentGreen = "Green",
    accentEmerald = "Emerald",
    accentTeal = "Teal",
    accentAzure = "Azure",
    accentBlue = "Blue",
    accentIndigo = "Indigo",
    accentViolet = "Violet",
    accentLilac = "Lilac",
    accentPink = "Pink",
    typeface = "Font",
    typefaceSystem = "System",
    typefaceSans = "Sans-serif",
    typefaceSerif = "Serif",
    typefaceMono = "Monospace",
    textScale = "Size",
    textScaleHint = "Dense for the goods list, the large steps for the till: the total reads from a metre away.",
    textScaleDense = "Dense",
    textScaleCompact = "Compact",
    textScaleNormal = "Regular",
    textScaleLarge = "Large",
    textScaleLarger = "Larger"
)
