package kz.mybrain.superkassa.desktop.ui.strings

/**
 * Надписи служебных разделов на этом языке.
 *
 * Настройки, показ печатной формы и словари состояний вынесены из общего
 * набора: одних настроек сто строк, и рядом с ними надписи продажи
 * не найти глазами.
 */

internal val russianSettings = SettingStrings(
    title = "Настройки",
    currentKkm = "Касса в работе",
    changeKkm = "Сменить кассу",
    registerKkm = "Завести кассу",
    back = "Назад",
    registerKkmHint = "Первую кассу заводят до входа: сначала узел выдаёт заводской номер, " +
        "потом кассу ставят на учёт в кабинете ОФД и вводят выданные идентификатор и токен.",
    kkmIdentifier = "Идентификатор ККМ",
    token = "Токен",
    adminPin = "Пин администратора",
    registering = "Заводится…",
    register = "Завести",
    registered = "Касса заведена, состояние",
    registerHint = "Пин администратора задаётся здесь и другого у новой кассы не будет: " +
        "по стандартному узел не пускает, а сменить его можно только войдя. " +
        "Кассиры и их пины заводятся потом, в разделе «Кассиры и пины».",
    diagnostics = "Диагностика",
    ofdLink = "Связь с ОФД",
    checkOfdLink = "Проверить связь с ОФД",
    ofdAnswers = "ОФД отвечает",
    ofdSilent = "ОФД не отвечает",
    ofdInfo = "Сведения об ОФД",
    programmingMode = "Режим программирования",
    enterProgramming = "Войти в программирование",
    exitProgramming = "Выйти",
    enteredProgramming = "Касса переведена в режим программирования",
    exitedProgramming = "Касса выведена из режима программирования",
    ofd = "ОФД",
    environment = "Контур",
    language = "Язык",
    appearance = "Оформление",
    ofdToken = "Токен ОФД",
    newToken = "Новый токен",
    saveToken = "Сохранить токен",
    tokenSaved = "Токен сохранён",
    tokenHint = "Токен выдаёт ОФД. По ответу «неверный токен» касса встаёт " +
        "и работает снова только после ввода нового.",
    printForm = "Печатный чек",
    programmingRequired = "Настройки кассы меняются в режиме программирования.",
    printFormSaved = "Настройки чека сохранены",
    receiptLanguage = "Язык чека",
    receiptBoth = "Два языка",
    receiptKk = "Қазақша",
    receiptRu = "Русский",
    paperWidth = "Ширина ленты",
    printLayout = "Макет печати",
    printer = "Принтер кассы",
    printerHint = "Принтер держится за кассой: за одним компьютером их бывает две, " +
        "и чековая лента у каждой своя. Пока не выбран, задание уходит на системный по умолчанию.",
    printerSystem = "Системный по умолчанию",
    printKind = "Вид файла при сохранении",
    printCopies = "Копий при печати",
    panelBehaviour = "Разделы кассовой колонки",
    taxSettings = "Налоги кассы",
    taxRegime = "Налоговый режим",
    defaultVatGroup = "Ставка по умолчанию",
    autoCloseShift = "Закрывать смену самостоятельно",
    autoCloseShiftHint = "Смена живёт сутки. Узел закроет её сам, если кассир не успел — Z-отчёт всё равно будет снят вовремя.",
    settingsSaved = "Настройки кассы сохранены",
    node = "Узел",
    nodeVersion = "Версия",
    nodeCoreVersion = "Версия ядра",
    nodeMode = "Режим",
    nodeProtocol = "Версия протокола",
    nodeStorage = "Хранилище",
    nodeHealth = "Состояние",
    ofdAuth = "Данные авторизации ОФД",
    ofdNextReqNum = "Номер следующего запроса",
    nodeUnknown = "Узел не ответил",
    nodeAddress = "Адрес узла",
    nodeAddressHint = "Узел обычно стоит на этой же машине. Новый адрес действует со следующего обращения, перезапуск не нужен",
    workplace = "Настройки рабочего места",
    mapServices = "Службы карты",
    mapServicesHint = "Пока адрес не задан, работает общедоступная карта сообщества: на всех владельцев она не рассчитана",
    mapTiles = "Плитки карты",
    mapSearch = "Поиск адреса",
    mapReverse = "Адрес по метке",
    mapLocation = "Определение места",
    mapDefault = "Вернуть общедоступные",
    groupAppearance = "Оформление и печать",
    groupService = "Обслуживание",
    groupIrreversible = "Необратимое",
    panelBehaviourHint = "Выбранное здесь — то, что кассир увидит при открытии продажи. " +
        "Свернуть или развернуть раздел он всё равно может стрелкой на самом экране.",
    panelPositionEntry = "Новая позиция",
    panelReceiptDetails = "Реквизиты чека",
    panelMoney = "Оплата и итог",
    printLayoutHint = "Лента 58 и 80 мм — для чековых принтеров, страница — для печати на обычном листе " +
        "и для отправки покупателю.",
    layoutTape58 = "Лента 58 мм",
    layoutTape80 = "Лента 80 мм",
    layoutFullscreen = "Полная страница",
    printOfdAds = "Печатать рекламу ОФД",
    printOfdAdsHint = "Строки приходят вместе с ответом на чек и печатаются под итогом.",
    receiptLines = "Свои строки на чеке",
    receiptLinesHint = "Реклама оператора приходит от ОФД, а это строки самой торговой точки: " +
        "приветствие, условия возврата, благодарность. Пустое поле не печатается.",
    saveReceiptLines = "Сохранить строки",
    lineBeforeHeader = "Над шапкой",
    lineHeader = "В шапке",
    lineAfterHeader = "Под шапкой",
    lineBeforeItems = "Перед позициями",
    lineAfterItems = "После позиций",
    lineBeforeTotals = "Перед итогом",
    lineAfterTotals = "После итога",
    lineBeforeQr = "Перед QR-кодом",
    lineFooter = "В подвале",
    appearanceSystem = "Как в системе",
    appearanceLight = "Светлая",
    appearanceDark = "Тёмная",
    factoryStep = "Шаг 1. Заводские данные",
    generateFactory = "Сгенерировать",
    factoryNumber = "Заводской номер",
    manufactureYear = "Год выпуска",
    factoryHint = "Заводской номер выдаёт узел по алгоритму производителя. " +
        "Отнесите его вместе с годом выпуска в ОФД: там кассу поставят на учёт " +
        "и выдадут идентификатор и токен.",
    ofdStep = "Шаг 2. Данные от ОФД",
    localName = "Название кассы",
    localNameHint = "Название хранится на узле: его видно за любым рабочим местом " +
        "и на экране входа. Прочие сведения приходят от ОФД и здесь не меняются.",
    save = "Сохранить"
)

internal val russianPreview = PreviewStrings(
    title = "Печатная форма",
    narrower = "Уже",
    wider = "Шире",
    close = "Закрыть",
    missing = "Узел не отдал печатную форму",
    print = "Печать",
    printSent = "Отправлено на принтер",
    printFailed = "Принтер не принял задание",
    save = "Сохранить в файл",
    saved = "Сохранено",
    zoomIn = "Крупнее",
    zoomOut = "Мельче",
    fit = "По ширине",
    drawPin = "Пин кассы",
    drawPinHint = "Печатную форму рисует касса, и узел пускает к ней по пину. " +
        "Пин остаётся только в памяти приложения и разделы кассы не открывает.",
    draw = "Показать форму",
    noDrawer = "Узел не отдал ни одной кассы — печатную форму рисовать нечем."
)

internal val russianStatus = StatusStrings(
    delivered = "Доставлен",
    resent = "Досланный",
    refused = "Отклонён",
    internal = "Внутренний",
    queued = "В очереди"
)

internal val russianEnums = EnumStrings(
    vatNone = "Без НДС",
    vat0 = "НДС 0%",
    vat5 = "НДС 5%",
    vat10 = "НДС 10%",
    vat16 = "НДС 16%",
    paymentCash = "Наличные",
    paymentCard = "Карта",
    paymentElectronic = "Электронные",
    paymentMobile = "Мобильный платёж",
    paymentCredit = "В кредит",
    paymentTare = "Тарой",
    domainTrading = "Торговля",
    domainServices = "Услуги",
    domainHotels = "Гостиницы",
    domainGasOil = "Нефтепродукты",
    domainTaxi = "Такси",
    domainParking = "Стоянка",
    docCheck = "Чек",
    docShiftOpen = "Открытие смены",
    docShiftClose = "Закрытие смены",
    docCashIn = "Внесение",
    docCashOut = "Изъятие",
    docReportX = "X-отчёт",
    stateActive = "В работе",
    stateIdle = "Готова к работе",
    stateBlocked = "Заблокирована",
    stateProgramming = "Программирование",
    stateRegistration = "Регистрация"
)
