package kz.mybrain.superkassa.desktop.ui.strings

/**
 * Надписи служебных разделов.
 *
 * Очередь, кассиры, настройки, показ печатной формы и словари состояний —
 * то, что открывают редко и осознанно.
 */

data class QueueStrings(
    val title: String,
    val empty: String,
    val waiting: String,
    val attempts: String,
    val retryFailed: String,
    val retryDone: String
)

data class UserStrings(
    val title: String,
    val name: String,
    val create: String,
    val created: String,
    val forbiddenPin: String,
    val newPin: String,
    val change: String,
    val changed: String,
    val delete: String,
    val deleted: String,
    val role: String,
    val admin: String,
    val cashier: String
)

data class SettingStrings(
    val title: String,
    val currentKkm: String,
    val changeKkm: String,
    val registerKkm: String,
    val back: String,
    val registerKkmHint: String,
    val kkmIdentifier: String,
    val token: String,
    val adminPin: String,
    val registering: String,
    val register: String,
    val registered: String,
    val registerHint: String,
    val diagnostics: String,
    val ofdLink: String,
    val checkOfdLink: String,
    val ofdAnswers: String,
    val ofdSilent: String,
    val ofdInfo: String,
    val programmingMode: String,
    val enterProgramming: String,
    val exitProgramming: String,
    /** Плашка состояния: касса сейчас в режиме программирования. */
    val programmingOn: String,
    val enteredProgramming: String,
    val exitedProgramming: String,
    val ofd: String,
    val environment: String,
    val language: String,
    val appearance: String,
    val appearanceHint: String,
    val look: LookStrings,
    val ofdToken: String,
    val newToken: String,
    val saveToken: String,
    val tokenSaved: String,
    val tokenHint: String,
    val printForm: String,
    val printFormHint: String,
    val programmingRequired: String,
    val printFormSaved: String,
    val receiptLanguage: String,
    val receiptBoth: String,
    val receiptKk: String,
    val receiptRu: String,
    val paperWidth: String,
    val printLayout: String,
    val printer: String,
    val printerHint: String,
    val printerSystem: String,
    /** На машине нет ни одного принтера: печатать чек некуда. */
    val printerNone: String,
    val printKind: String,
    val printCopies: String,
    val panelBehaviour: String,
    val taxSettings: String,
    val taxSettingsHint: String,
    val taxRegime: String,
    val defaultVatGroup: String,
    /** Справочники узла не прочитаны: выбирать не из чего и незачем. */
    val dictionariesMissing: String,
    val dictionariesMissingHint: String,
    val autoCashout: String,
    val autoCashoutHint: String,
    val settingsSaved: String,
    val node: String,
    val nodeHint: String,
    val nodeVersion: String,
    /** Версия ядра внутри узла. */
    val nodeCoreVersion: String,
    val nodeMode: String,
    val nodeProtocol: String,
    val nodeStorage: String,
    val nodeRenderer: String,
    val nodeRendererMissing: String,
    val nodeHealth: String,
    val ofdAuth: String,
    val ofdNextReqNum: String,
    val nodeUnknown: String,
    val nodeAddress: String,
    val nodeAddressHint: String,
    val workplace: String,
    val mapServices: String,
    val mapServicesHint: String,
    val mapTiles: String,
    val mapSearch: String,
    val mapReverse: String,
    val mapLocation: String,
    val mapDefault: String,
    /** Хозяйства настроек: где именно изменится выбранное. */
    val householdWorkplace: String,
    val householdKkm: String,
    val householdCabinet: String,
    /** Как печатает эта касса: форма на узле, принтер на этой машине. */
    val groupPrinting: String,
    /** Настройки самой кассы: их принимает узел и только в режиме программирования. */
    val groupService: String,
    /** Адреса служб, с которыми говорит рабочее место: узел, кабинет, карта. */
    val groupServices: String,
    /** Сама программа на этой машине: журнал, версия, сведения об узле. */
    val groupProgram: String,
    val groupIrreversible: String,
    val panelBehaviourHint: String,
    val panelPositionEntry: String,
    val panelReceiptDetails: String,
    val panelMoney: String,
    val printLayoutHint: String,
    val layoutTape58: String,
    val layoutTape80: String,
    val layoutFullscreen: String,
    val printOfdAds: String,
    val printOfdAdsHint: String,
    val receiptLines: String,
    val receiptLinesHint: String,
    val saveReceiptLines: String,
    val lineBeforeHeader: String,
    val lineHeader: String,
    val lineAfterHeader: String,
    val lineBeforeItems: String,
    val lineAfterItems: String,
    val lineBeforeTotals: String,
    val lineAfterTotals: String,
    val lineBeforeQr: String,
    val lineFooter: String,
    val appearanceSystem: String,
    val appearanceLight: String,
    val appearanceDark: String,
    val factoryStep: String,
    val generateFactory: String,
    val factoryNumber: String,
    val manufactureYear: String,
    val factoryHint: String,
    val ofdStep: String,
    val localName: String,
    val localNameHint: String,
    val save: String
)
