package kz.mybrain.superkassa.desktop.ui.strings

/** Русский текст интерфейса. */
internal val RussianStrings = AppStrings(
    common = CommonStrings(
        refresh = "Обновить",
        hide = "Скрыть",
        print = "Печать",
        amount = "Сумма",
        pin = "Пин",
        loading = "Читается…",
        nodeOnline = "Узел на связи",
        nodeOffline = "Узел недоступен",
        nodeUnavailable = "Узел кассы недоступен",
        nodeNoAnswer = "Ответ не получен — документ мог быть проведён, проверьте журнал; повтор не задвоит",
        refusalCode = "Код отказа",
        deliveredToOfd = "доставлено в БФД",
        queuedNoLink = "связи нет — поставлено в очередь",
        deliveryState = "состояние доставки",
        collapse = "Свернуть",
        explain = "Пояснение",
        expand = "Развернуть",
        retry = "Повторить",
        nothingToPick = "Выбирать не из чего"
    ),
    login = LoginStrings(
        title = "Вход в кассу",
        search = "Поиск: номер, название, организация",
        noKkmsTitle = "На этом узле ни одной кассы",
        noKkms = "Узел не отдал ни одной кассы. Заведите кассу в настройках или проверьте связь с узлом.",
        nodeSilentTitle = "Узел не ответил",
        nodeSilent = "Список касс прочитать не удалось, и сколько касс на этом узле — неизвестно. " +
            "Проверьте адрес узла в настройках и повторите.",
        yourKkm = "Ваша касса",
        pick = "Выбрать",
        picked = "Выбрана",
        enter = "Войти",
        reload = "Перечитать список",
        noKkmChosen = "Касса не выбрана",
        pickHint = "Выберите кассу в списке",
        factory = "Заводской",
        // Номер один, и имя у него одно: «РНМ» здесь и «Номер КГД»
        // в таблицах кабинета читались как два разных номера.
        registrationNumber = "Номер КГД"
    ),
    shell = ShellStrings(
        noKkm = "Касса не выбрана",
        autonomous = "Автономный режим",
        blocked = "Заблокирована",
        changeCashier = "Сменить кассира"
    ),
    sections = SectionStrings(
        dashboard = "Главная",
        sale = "Продажа",
        returns = "Возврат",
        cash = "Деньги",
        history = "История",
        queue = "Очередь",
        users = "Кассиры",
        settings = "Настройки",
        register = "Новая касса",
        cabinet = "Кабинет БФД"
    ),
    dashboard = DashboardStrings(
        state = "Состояние",
        shift = "Смена",
        shiftOpenNo = "№ %s открыта",
        shiftClosed = "Закрыта",
        documentsInShift = "Документов за смену",
        shiftDocuments = "Документы смены",
        refused = "Отклонено БФД",
        refusedHint = "Эти документы БФД не приняла: фискальными они не стали, в счётчики смены не вошли " +
            "и печатной формы у них нет. Код отказа и кассир нужны обслуживанию.",
        openShift = "Открыть смену",
        xReport = "X-отчёт",
        closeShift = "Закрыть смену",
        closeShiftAsk = "Закрыть смену и снять Z-отчёт?",
        closeShiftExplain = "В смене документов: %s, в ящике %s. Z-отчёт уйдёт в БФД, и смена не отменяется.",
        closeShiftCashout = "Остаток наличных уйдёт изъятием вместе с отчётом.",
        closeShiftKeepsCash = "Остаток наличных останется в ящике и перейдёт в новую смену.",
        openShiftHint = "Смена закрыта — откройте смену, чтобы пробивать чеки",
        openShiftAdmin = "Смену открывает администратор — позовите его, чтобы начать день.",
        shiftOpened = "Смена открыта",
        shiftClosedDone = "Смена закрыта, Z-отчёт отправлен",
        xReportDone = "X-отчёт сформирован",
        printForm = "Печатная форма",
        shiftUnknown = "Неизвестна",
        shiftEmpty = "Документов пока нет",
        shiftEmptyHint = "Смена открыта: первый чек появится здесь сразу после проведения.",
        shiftUnknownHint = "Узел не назвал состояние смены — проверьте связь с ним в настройках.",
        documentNo = "№"

    ),
    autonomous = AutonomousStrings(
        title = "Автономный режим",
        explain = "Связи с БФД нет. Чеки пробиваются и получают автономный признак, " +
            "а в БФД уходят сами, как только связь появится. Работать можно.",
        waiting = "Ждут отправки",
        checkLink = "Проверить связь",
        sendQueued = "Отправить накопленное",
        sendQueuedRules = "Досылку накопленного делает администратор: смена должна быть закрыта, а касса переведена в режим программирования.",
        linkBack = "Связь с БФД восстановлена"
    ),
    sale = SaleStrings(
        receipt = "Чек",
        sale = "Продажа",
        purchase = "Покупка",
        issueSale = "Пробить чек",
        issuePurchase = "Оформить покупку",
        issuing = "Оформляется…",
        name = "Наименование",
        price = "Цена",
        quantity = "Количество",
        measureUnit = "Единица измерения",
        vat = "НДС",
        discount = "Скидка",
        storno = "Сторно",
        stornoUndo = "Снять сторно",
        add = "Добавить",
        remove = "Убрать",
        clearBasket = "Очистить корзину",
        receiptDiscount = "Скидка на чек",
        receiptMarkup = "Наценка на чек",
        discountOrMarkup = "Скидка и наценка на чек — одна или другая",
        customerBin = "ИИН/БИН покупателя",
        taken = "Принято",
        total = "Итого",
        domainHint = "Заполните реквизиты выбранного вида отрасли — без них БФД чек отвергнет.",
        barcode = "Штрихкод",
        barcodeSearch = "Поиск по штрихкоду",
        barcodeSearching = "Ищется…",
        barcodeFind = "Найти",
        barcodeMissing = "В справочнике нет такого штрихкода — добавьте позицию вручную.",
        barcodeUnavailable = "Справочник сейчас недоступен — добавьте позицию вручную.",
        domainKind = "Вид отрасли",
        accountNumber = "Номер счёта",
        cardNumber = "Номер карты",
        carNumber = "Номер машины",
        fee = "Тариф",
        byOrder = "По заказу",
        parkingHours = "Часов стоянки",
        payment = "Вид оплаты",
        delivered = "чек пробит и доставлен в БФД",
        queued = "чек пробит, связи нет — поставлен в очередь",
        deliveryState = "состояние доставки"
    ),
    returns = ReturnStrings(
        title = "Возврат",
        empty = "В текущей смене нет чеков, по которым можно оформить возврат.",
        receiptNo = "Чек №",
        refundFor = "Возврат по чеку №",
        saleReturn = "Возврат продажи",
        giveBack = "Вернуть покупателю",
        purchaseReturn = "Возврат покупки",
        takeBack = "Принять обратно",
        done = "оформлен, состояние"
    ),
    cash = CashStrings(
        deposit = "Внести",
        withdraw = "Изъять",
        deposited = "Внесено",
        withdrawn = "Изъято"
    ),
    queue = QueueStrings(
        title = "Очередь отправки",
        empty = "Ждущих документов нет — всё доставлено в БФД.",
        waiting = "Ждут отправки",
        attempts = "Попыток",
        retryFailed = "Повторить неудачные",
        retryDone = "Неудачные задачи поставлены на повтор"
    ),
    users = UserStrings(
        title = "Кассиры и пины",
        name = "Имя",
        create = "Завести",
        created = "заведён",
        forbiddenPin = "Такой пин узел не примет: стандартные пины запрещены.",
        newPin = "Новый пин",
        change = "Сменить",
        changed = "Пин изменён",
        delete = "Удалить",
        deleted = "удалён",
        role = "Роль",
        admin = "Администратор",
        cashier = "Кассир"
    ),
    settings = russianSettings,
    preview = russianPreview,
    status = russianStatus,
    enums = russianEnums
)
