package kz.mybrain.superkassa.desktop.ui.strings

/** Қазақ тіліндегі интерфейс мәтіні. */
internal val KazakhStrings = AppStrings(
    common = CommonStrings(
        refresh = "Жаңарту",
        hide = "Жасыру",
        print = "Басып шығару",
        amount = "Сома",
        pin = "ПИН",
        loading = "Оқылуда…",
        nodeOnline = "Түйін байланыста",
        nodeOffline = "Түйін қолжетімсіз",
        nodeUnavailable = "Касса түйіні қолжетімсіз",
        refusalCode = "Бас тарту коды",
        deliveredToOfd = "ОФД-ға жеткізілді",
        queuedNoLink = "байланыс жоқ — кезекке қойылды",
        deliveryState = "жеткізу күйі",
        collapse = "Жию",
        explain = "Түсіндірме",
        expand = "Жаю"
    ),
    login = LoginStrings(
        title = "Кассаға кіру",
        search = "Іздеу: нөмір, атауы, ұйым",
        noKkms = "Түйін бірде-бір касса бермеді. Баптауларда касса тіркеңіз немесе байланысты тексеріңіз.",
        yourKkm = "Сіздің кассаңыз",
        pick = "Таңдау",
        picked = "Таңдалды",
        enter = "Кіру",
        reload = "Тізімді жаңарту",
        noKkmChosen = "Касса таңдалмады",
        pickHint = "Тізімнен кассаны таңдаңыз",
        factory = "Зауыттық"
    ),
    shell = ShellStrings(
        noKkm = "Касса таңдалмады",
        autonomous = "Дербес режим",
        blocked = "Бұғатталған",
        changeCashier = "Кассирді ауыстыру"
    ),
    sections = SectionStrings(
        dashboard = "Басты бет",
        sale = "Сату",
        returns = "Қайтару",
        cash = "Ақша",
        history = "Тарих",
        queue = "Кезек",
        users = "Кассирлер",
        settings = "Баптаулар",
        register = "Жаңа касса",
        cabinet = "ОФД кабинеті"
    ),
    dashboard = DashboardStrings(
        state = "Күйі",
        shift = "Ауысым",
        shiftOpenNo = "№ %s ашық",
        shiftClosed = "Жабық",
        cashInDrawer = "Кассадағы қолма-қол ақша",
        documentsInShift = "Ауысымдағы құжаттар",
        shiftDocuments = "Ауысым құжаттары",
        refused = "ОФД қабылдамады",
        refusedHint = "Бұл құжаттарды ОФД қабылдамады: олар фискалдық болмады, ауысым есептеуішіне кірмеді " +
            "және баспа түрі жоқ. Бас тарту коды мен кассир қызмет көрсетуге қажет.",
        openShift = "Ауысымды ашу",
        xReport = "X-есеп",
        closeShift = "Ауысымды жабу",
        openShiftHint = "Ауысым жабық — чек басу үшін ауысымды ашыңыз",
        openShiftAdmin = "Ауысымды әкімші ашады — күнді бастау үшін оны шақырыңыз.",
        shiftOpened = "Ауысым ашылды",
        shiftClosedDone = "Ауысым жабылды, Z-есеп жіберілді",
        xReportDone = "X-есеп жасалды",
        printForm = "Басып шығару пішіні"

    ),
    autonomous = AutonomousStrings(
        title = "Дербес режим",
        explain = "ОФД-мен байланыс жоқ. Чектер басылып, дербес белгі алады, " +
            "ал байланыс пайда болған бойда ОФД-ға өздері жіберіледі. Жұмысты жалғастыруға болады.",
        waiting = "Жіберуді күтуде",
        checkLink = "Байланысты тексеру",
        sendQueued = "Жиналғанды жіберу",
        sendQueuedRules = "Жинақталғанды әкімші жібереді: ауысым жабық болуы және касса бағдарламалау режимінде болуы керек.",
        linkBack = "ОФД-мен байланыс қалпына келді"
    ),
    sale = SaleStrings(
        receipt = "Чек",
        sale = "Сату",
        purchase = "Сатып алу",
        issueSale = "Чекті басу",
        issuePurchase = "Сатып алуды ресімдеу",
        issuing = "Ресімделуде…",
        name = "Атауы",
        price = "Бағасы",
        quantity = "Саны",
        vat = "ҚҚС",
        discount = "Жеңілдік",
        storno = "Сторно",
        add = "Қосу",
        remove = "Алып тастау",
        clearBasket = "Себетті тазалау",
        receiptDiscount = "Чекке жеңілдік",
        receiptMarkup = "Чекке үстеме",
        discountOrMarkup = "Чекке жеңілдік пен үстеме — біреуі ғана",
        customerBin = "Сатып алушының ЖСН/БСН",
        taken = "Қабылданды",
        total = "Барлығы",
        domainHint = "Таңдалған сала деректемелерін толтырыңыз — оларсыз ОФД чекті қабылдамайды.",
        barcode = "Штрих-код",
        barcodeSearch = "Штрих-код бойынша іздеу",
        barcodeSearching = "Ізделуде…",
        barcodeFind = "Табу",
        barcodeMissing = "Анықтамалықта мұндай штрих-код жоқ — позицияны қолмен қосыңыз.",
        domainKind = "Сала түрі",
        accountNumber = "Шот нөмірі",
        cardNumber = "Карта нөмірі",
        carNumber = "Көлік нөмірі",
        fee = "Тариф",
        byOrder = "Тапсырыс бойынша",
        parkingHours = "Тұрақ сағаттары",
        payment = "Төлем түрі",
        delivered = "чек басылды және ОФД-ға жеткізілді",
        queued = "чек басылды, байланыс жоқ — кезекке қойылды",
        deliveryState = "жеткізу күйі"
    ),
    returns = ReturnStrings(
        title = "Қайтару",
        empty = "Ағымдағы ауысымда қайтаруға негіз болатын чек жоқ.",
        receiptNo = "Чек №",
        refundFor = "№ чек бойынша қайтару",
        saleReturn = "Сатуды қайтару",
        giveBack = "Сатып алушыға қайтару",
        purchaseReturn = "Сатып алуды қайтару",
        takeBack = "Кері қабылдау",
        done = "ресімделді, күйі"
    ),
    cash = CashStrings(
        title = "Кассадағы ақша",
        inDrawer = "Жәшікте",
        deposit = "Салу",
        withdraw = "Алу",
        deposited = "Салынды",
        withdrawn = "Алынды"
    ),
    history = HistoryStrings(
        title = "Тәулік тарихы",
        load = "Жүктеу",
        loading = "Оқылуда…"
    ),
    queue = QueueStrings(
        title = "Жіберу кезегі",
        empty = "Күтіп тұрған құжат жоқ — бәрі ОФД-ға жеткізілді.",
        waiting = "Жіберуді күтуде",
        attempts = "Әрекеттер",
        retryFailed = "Сәтсіздерді қайталау",
        retryDone = "Сәтсіз тапсырмалар қайталауға қойылды"
    ),
    users = UserStrings(
        title = "Кассирлер мен пиндер",
        name = "Аты",
        create = "Тіркеу",
        created = "тіркелді",
        forbiddenPin = "Мұндай пинді түйін қабылдамайды: стандартты пиндерге тыйым салынған.",
        newPin = "Жаңа пин",
        change = "Ауыстыру",
        changed = "Пин ауыстырылды",
        delete = "Жою",
        deleted = "жойылды",
        role = "Рөлі",
        admin = "Әкімші",
        cashier = "Кассир"
    ),
    settings = SettingStrings(
        title = "Баптаулар",
        currentKkm = "Жұмыстағы касса",
        changeKkm = "Кассаны ауыстыру",
        registerKkm = "Касса тіркеу",
        back = "Артқа",
        registerKkmHint = "Алғашқы кассаны кіргенге дейін тіркейді: алдымен түйін зауыттық нөмір береді, " +
            "содан кейін касса ОФД кабинетінде есепке қойылып, берілген сәйкестендіргіш пен токен енгізіледі.",
        kkmIdentifier = "БКМ идентификаторы",
        token = "Токен",
        adminPin = "Әкімші пині",
        registering = "Тіркелуде…",
        register = "Тіркеу",
        registered = "Касса тіркелді, күйі",
        registerHint = "Әкімшінің пині осында беріледі, жаңа кассада басқасы болмайды: " +
            "стандартты пинмен түйін кіргізбейді, ал оны кіргеннен кейін ғана ауыстыруға болады. " +
            "Кассирлер мен олардың пиндері кейін «Кассирлер мен пиндер» бөлімінде тіркеледі.",
        diagnostics = "Диагностика",
        ofdLink = "ОФД байланысы",
        checkOfdLink = "ОФД байланысын тексеру",
        ofdAnswers = "ОФД жауап береді",
        ofdSilent = "ОФД жауап бермейді",
        ofdInfo = "ОФД туралы мәліметтер",
        programmingMode = "Бағдарламалау режимі",
        enterProgramming = "Бағдарламалауға кіру",
        exitProgramming = "Шығу",
        enteredProgramming = "Касса бағдарламалау режиміне ауыстырылды",
        exitedProgramming = "Касса бағдарламалау режимінен шығарылды",
        ofd = "ОФД",
        environment = "Контур",
        language = "Тіл",
        appearance = "Безендіру",
        ofdToken = "ОФД токені",
        newToken = "Жаңа токен",
        saveToken = "Токенді сақтау",
        tokenSaved = "Токен сақталды",
        tokenHint = "Токенді ОФД береді. «Токен жарамсыз» жауабынан кейін касса тоқтайды " +
            "және тек жаңа токен енгізілгенде қайта жұмыс істейді.",
        printForm = "Басып шығару пішіні",
        programmingRequired = "Касса баптаулары бағдарламалау режимінде өзгертіледі.",
        printFormSaved = "Чек баптаулары сақталды",
        receiptLanguage = "Чек тілі",
        receiptBoth = "Екі тіл",
        receiptKk = "Қазақша",
        receiptRu = "Русский",
        paperWidth = "Таспа ені",
        printLayout = "Басып шығару макеті",
        printer = "Касса принтері",
        printerHint = "Принтер кассаға бекітіледі: бір компьютерде екеуі болуы мүмкін, " +
            "әрқайсысының чек таспасы бөлек. Таңдалмаған кезде тапсырма жүйелік принтерге кетеді.",
        printerSystem = "Жүйелік әдепкі",
        printKind = "Сақтау кезіндегі файл түрі",
        printCopies = "Басып шығару даналары",
        panelBehaviour = "Касса бағанының бөлімдері",
        groupAppearance = "Безендіру және басып шығару",
        groupService = "Қызмет көрсету",
        groupIrreversible = "Қайтарымсыз",
        panelBehaviourHint = "Мұнда таңдалғанды кассир сатуды ашқанда көреді. " +
            "Бөлімді экранның өзінде де көрсеткішпен жинауға немесе жаюға болады.",
        panelPositionEntry = "Жаңа позиция",
        panelReceiptDetails = "Чек деректемелері",
        panelMoney = "Төлем және қорытынды",
        printLayoutHint = "58 және 80 мм таспа — чек принтерлеріне, бет — кәдімгі параққа басып шығаруға " +
            "және сатып алушыға жіберуге.",
        layoutTape58 = "58 мм таспа",
        layoutTape80 = "80 мм таспа",
        layoutFullscreen = "Толық бет",
        printOfdAds = "ОФД жарнамасын басып шығару",
        printOfdAdsHint = "Жолдар чекке жауаппен бірге келеді және қорытынды астында басылады.",
        receiptLines = "Чектегі өз жолдарыңыз",
        receiptLinesHint = "Оператордың жарнамасы ОФД-дан келеді, ал бұл — сауда нүктесінің өз жолдары: " +
            "сәлемдесу, қайтару шарттары, алғыс. Бос өріс басылмайды.",
        saveReceiptLines = "Жолдарды сақтау",
        lineBeforeHeader = "Тақырып үстінде",
        lineHeader = "Тақырыпта",
        lineAfterHeader = "Тақырып астында",
        lineBeforeItems = "Позициялар алдында",
        lineAfterItems = "Позициялардан кейін",
        lineBeforeTotals = "Қорытынды алдында",
        lineAfterTotals = "Қорытындыдан кейін",
        lineBeforeQr = "QR-код алдында",
        lineFooter = "Төменгі жолда",
        appearanceSystem = "Жүйедегідей",
        appearanceLight = "Ашық",
        appearanceDark = "Күңгірт",
        factoryStep = "1-қадам. Зауыттық деректер",
        generateFactory = "Жасау",
        factoryNumber = "Зауыттық нөмір",
        manufactureYear = "Шығарылған жылы",
        factoryHint = "Зауыттық нөмірді түйін өндіруші алгоритмі бойынша береді. " +
            "Оны шығарылған жылымен бірге ОФД-ға апарыңыз: сонда касса есепке қойылып, " +
            "идентификатор мен токен беріледі.",
        ofdStep = "2-қадам. ОФД деректері",
        localName = "Кассаның өз атауы",
        localNameHint = "Атау тек осы жұмыс орнында көрінеді. " +
            "Касса туралы мәліметтер ОФД-дан келеді және мұнда өзгермейді.",
        save = "Сақтау"
    ),
    preview = PreviewStrings(
        title = "Басып шығару пішіні",
        narrower = "Тарырақ",
        wider = "Кеңірек",
        close = "Жабу",
        missing = "Түйін басып шығару пішінін бермеді",
        print = "Басып шығару",
        printSent = "Принтерге жіберілді",
        printFailed = "Принтер тапсырманы қабылдамады",
        save = "Файлға сақтау",
        saved = "Сақталды",
        zoomIn = "Үлкейту",
        zoomOut = "Кішірейту",
        fit = "Ені бойынша"
    ),
    status = StatusStrings(
        delivered = "Жеткізілді",
        resent = "Кейін жіберілген",
        refused = "Қабылданбады",
        internal = "Ішкі",
        queued = "Кезекте"
    ),
    enums = EnumStrings(
        vatNone = "ҚҚС-сыз",
        vat0 = "ҚҚС 0%",
        vat5 = "ҚҚС 5%",
        vat10 = "ҚҚС 10%",
        vat16 = "ҚҚС 16%",
        paymentCash = "Қолма-қол",
        paymentCard = "Карта",
        paymentElectronic = "Электрондық",
        paymentMobile = "Мобильді төлем",
        paymentCredit = "Несиеге",
        paymentTare = "Ыдыспен",
        domainTrading = "Сауда",
        domainServices = "Қызметтер",
        domainHotels = "Қонақүйлер",
        domainGasOil = "Мұнай өнімдері",
        domainTaxi = "Такси",
        domainParking = "Тұрақ",
        docCheck = "Чек",
        docShiftOpen = "Ауысымды ашу",
        docShiftClose = "Ауысымды жабу",
        docCashIn = "Салу",
        docCashOut = "Алу",
        docReportX = "X-есеп",
        stateActive = "Жұмыста",
        stateIdle = "Жұмысқа дайын",
        stateBlocked = "Бұғатталған",
        stateProgramming = "Бағдарламалау",
        stateRegistration = "Тіркеу"
    )
)
