package kz.mybrain.superkassa.desktop.ui.strings

/** Русский текст интерфейса. */
internal val RussianStrings = AppStrings(
    common = CommonStrings(
        refresh = "Обновить",
        hide = "Скрыть",
        print = "Печать",
        amount = "Сумма",
        pin = "Пин",
        loading = "Читается…",
        nodeOnline = "Узел на связи",
        nodeOffline = "Узел недоступен",
        nodeUnavailable = "Узел кассы недоступен",
        refusalCode = "Код отказа",
        deliveredToOfd = "доставлено в ОФД",
        queuedNoLink = "связи нет — поставлено в очередь",
        deliveryState = "состояние доставки",
        collapse = "Свернуть",
        explain = "Пояснение",
        expand = "Развернуть"
    ),
    login = LoginStrings(
        title = "Вход в кассу",
        search = "Поиск: номер, название, организация",
        noKkms = "Узел не отдал ни одной кассы. Заведите кассу в настройках или проверьте связь с узлом.",
        yourKkm = "Ваша касса",
        pick = "Выбрать",
        picked = "Выбрана",
        enter = "Войти",
        reload = "Перечитать список",
        noKkmChosen = "Касса не выбрана",
        pickHint = "Выберите кассу в списке",
        factory = "Заводской"
    ),
    shell = ShellStrings(
        noKkm = "Касса не выбрана",
        autonomous = "Автономный режим",
        blocked = "Заблокирована",
        changeCashier = "Сменить кассира"
    ),
    sections = SectionStrings(
        dashboard = "Главная",
        sale = "Продажа",
        returns = "Возврат",
        cash = "Деньги",
        history = "История",
        queue = "Очередь",
        users = "Кассиры",
        settings = "Настройки",
        register = "Новая касса",
        cabinet = "Кабинет ОФД"
    ),
    dashboard = DashboardStrings(
        state = "Состояние",
        shift = "Смена",
        shiftOpenNo = "№ %s открыта",
        shiftClosed = "Закрыта",
        cashInDrawer = "Наличные в кассе",
        documentsInShift = "Документов за смену",
        shiftDocuments = "Документы смены",
        refused = "Отклонено ОФД",
        refusedHint = "Эти документы ОФД не принял: фискальными они не стали, в счётчики смены не вошли " +
            "и печатной формы у них нет. Код отказа и кассир нужны обслуживанию.",
        openShift = "Открыть смену",
        xReport = "X-отчёт",
        closeShift = "Закрыть смену",
        openShiftHint = "Смена закрыта — откройте смену, чтобы пробивать чеки",
        openShiftAdmin = "Смену открывает администратор — позовите его, чтобы начать день.",
        shiftOpened = "Смена открыта",
        shiftClosedDone = "Смена закрыта, Z-отчёт отправлен",
        xReportDone = "X-отчёт сформирован",
        printForm = "Печатная форма"

    ),
    autonomous = AutonomousStrings(
        title = "Автономный режим",
        explain = "Связи с ОФД нет. Чеки пробиваются и получают автономный признак, " +
            "а в ОФД уходят сами, как только связь появится. Работать можно.",
        waiting = "Ждут отправки",
        checkLink = "Проверить связь",
        sendQueued = "Отправить накопленное",
        sendQueuedRules = "Досылку накопленного делает администратор: смена должна быть закрыта, а касса переведена в режим программирования.",
        linkBack = "Связь с ОФД восстановлена"
    ),
    sale = SaleStrings(
        receipt = "Чек",
        sale = "Продажа",
        purchase = "Покупка",
        issueSale = "Пробить чек",
        issuePurchase = "Оформить покупку",
        issuing = "Оформляется…",
        name = "Наименование",
        price = "Цена",
        quantity = "Количество",
        vat = "НДС",
        discount = "Скидка",
        storno = "Сторно",
        add = "Добавить",
        remove = "Убрать",
        clearBasket = "Очистить корзину",
        receiptDiscount = "Скидка на чек",
        receiptMarkup = "Наценка на чек",
        discountOrMarkup = "Скидка и наценка на чек — одна или другая",
        customerBin = "ИИН/БИН покупателя",
        taken = "Принято",
        total = "Итого",
        domainHint = "Заполните реквизиты выбранного вида отрасли — без них ОФД чек отвергнет.",
        barcode = "Штрихкод",
        barcodeSearch = "Поиск по штрихкоду",
        barcodeSearching = "Ищется…",
        barcodeFind = "Найти",
        barcodeMissing = "В справочнике нет такого штрихкода — добавьте позицию вручную.",
        domainKind = "Вид отрасли",
        accountNumber = "Номер счёта",
        cardNumber = "Номер карты",
        carNumber = "Номер машины",
        fee = "Тариф",
        byOrder = "По заказу",
        parkingHours = "Часов стоянки",
        payment = "Вид оплаты",
        delivered = "чек пробит и доставлен в ОФД",
        queued = "чек пробит, связи нет — поставлен в очередь",
        deliveryState = "состояние доставки"
    ),
    returns = ReturnStrings(
        title = "Возврат",
        empty = "В текущей смене нет чеков, по которым можно оформить возврат.",
        receiptNo = "Чек №",
        refundFor = "Возврат по чеку №",
        saleReturn = "Возврат продажи",
        giveBack = "Вернуть покупателю",
        purchaseReturn = "Возврат покупки",
        takeBack = "Принять обратно",
        done = "оформлен, состояние"
    ),
    cash = CashStrings(
        title = "Деньги в кассе",
        inDrawer = "В ящике",
        deposit = "Внести",
        withdraw = "Изъять",
        deposited = "Внесено",
        withdrawn = "Изъято"
    ),
    history = HistoryStrings(
        title = "История за сутки",
        load = "Загрузить",
        loading = "Читается…"
    ),
    queue = QueueStrings(
        title = "Очередь отправки",
        empty = "Ждущих документов нет — всё доставлено в ОФД.",
        waiting = "Ждут отправки",
        attempts = "Попыток",
        retryFailed = "Повторить неудачные",
        retryDone = "Неудачные задачи поставлены на повтор"
    ),
    users = UserStrings(
        title = "Кассиры и пины",
        name = "Имя",
        create = "Завести",
        created = "заведён",
        forbiddenPin = "Такой пин узел не примет: стандартные пины запрещены.",
        newPin = "Новый пин",
        change = "Сменить",
        changed = "Пин изменён",
        delete = "Удалить",
        deleted = "удалён",
        role = "Роль",
        admin = "Администратор",
        cashier = "Кассир"
    ),
    settings = SettingStrings(
        title = "Настройки",
        currentKkm = "Касса в работе",
        changeKkm = "Сменить кассу",
        registerKkm = "Завести кассу",
        back = "Назад",
        registerKkmHint = "Первую кассу заводят до входа: сначала узел выдаёт заводской номер, " +
            "потом кассу ставят на учёт в кабинете ОФД и вводят выданные идентификатор и токен.",
        kkmIdentifier = "Идентификатор ККМ",
        token = "Токен",
        adminPin = "Пин администратора",
        registering = "Заводится…",
        register = "Завести",
        registered = "Касса заведена, состояние",
        registerHint = "Пин администратора задаётся здесь и другого у новой кассы не будет: " +
            "по стандартному узел не пускает, а сменить его можно только войдя. " +
            "Кассиры и их пины заводятся потом, в разделе «Кассиры и пины».",
        diagnostics = "Диагностика",
        ofdLink = "Связь с ОФД",
        checkOfdLink = "Проверить связь с ОФД",
        ofdAnswers = "ОФД отвечает",
        ofdSilent = "ОФД не отвечает",
        ofdInfo = "Сведения об ОФД",
        programmingMode = "Режим программирования",
        enterProgramming = "Войти в программирование",
        exitProgramming = "Выйти",
        enteredProgramming = "Касса переведена в режим программирования",
        exitedProgramming = "Касса выведена из режима программирования",
        ofd = "ОФД",
        environment = "Контур",
        language = "Язык",
        appearance = "Оформление",
        ofdToken = "Токен ОФД",
        newToken = "Новый токен",
        saveToken = "Сохранить токен",
        tokenSaved = "Токен сохранён",
        tokenHint = "Токен выдаёт ОФД. По ответу «неверный токен» касса встаёт " +
            "и работает снова только после ввода нового.",
        printForm = "Печатный чек",
        programmingRequired = "Настройки кассы меняются в режиме программирования.",
        printFormSaved = "Настройки чека сохранены",
        receiptLanguage = "Язык чека",
        receiptBoth = "Два языка",
        receiptKk = "Қазақша",
        receiptRu = "Русский",
        paperWidth = "Ширина ленты",
        printLayout = "Макет печати",
        printer = "Принтер кассы",
        printerHint = "Принтер держится за кассой: за одним компьютером их бывает две, " +
            "и чековая лента у каждой своя. Пока не выбран, задание уходит на системный по умолчанию.",
        printerSystem = "Системный по умолчанию",
        printKind = "Вид файла при сохранении",
        printCopies = "Копий при печати",
        panelBehaviour = "Разделы кассовой колонки",
        groupAppearance = "Оформление и печать",
        groupService = "Обслуживание",
        groupIrreversible = "Необратимое",
        panelBehaviourHint = "Выбранное здесь — то, что кассир увидит при открытии продажи. " +
            "Свернуть или развернуть раздел он всё равно может стрелкой на самом экране.",
        panelPositionEntry = "Новая позиция",
        panelReceiptDetails = "Реквизиты чека",
        panelMoney = "Оплата и итог",
        printLayoutHint = "Лента 58 и 80 мм — для чековых принтеров, страница — для печати на обычном листе " +
            "и для отправки покупателю.",
        layoutTape58 = "Лента 58 мм",
        layoutTape80 = "Лента 80 мм",
        layoutFullscreen = "Полная страница",
        printOfdAds = "Печатать рекламу ОФД",
        printOfdAdsHint = "Строки приходят вместе с ответом на чек и печатаются под итогом.",
        receiptLines = "Свои строки на чеке",
        receiptLinesHint = "Реклама оператора приходит от ОФД, а это строки самой торговой точки: " +
            "приветствие, условия возврата, благодарность. Пустое поле не печатается.",
        saveReceiptLines = "Сохранить строки",
        lineBeforeHeader = "Над шапкой",
        lineHeader = "В шапке",
        lineAfterHeader = "Под шапкой",
        lineBeforeItems = "Перед позициями",
        lineAfterItems = "После позиций",
        lineBeforeTotals = "Перед итогом",
        lineAfterTotals = "После итога",
        lineBeforeQr = "Перед QR-кодом",
        lineFooter = "В подвале",
        appearanceSystem = "Как в системе",
        appearanceLight = "Светлая",
        appearanceDark = "Тёмная",
        factoryStep = "Шаг 1. Заводские данные",
        generateFactory = "Сгенерировать",
        factoryNumber = "Заводской номер",
        manufactureYear = "Год выпуска",
        factoryHint = "Заводской номер выдаёт узел по алгоритму производителя. " +
            "Отнесите его вместе с годом выпуска в ОФД: там кассу поставят на учёт " +
            "и выдадут идентификатор и токен.",
        ofdStep = "Шаг 2. Данные от ОФД",
        localName = "Своё название кассы",
        localNameHint = "Название видно только на этом рабочем месте. " +
            "Сведения о кассе приходят от ОФД и здесь не меняются.",
        save = "Сохранить"
    ),
    preview = PreviewStrings(
        title = "Печатная форма",
        narrower = "Уже",
        wider = "Шире",
        close = "Закрыть",
        missing = "Узел не отдал печатную форму",
        print = "Печать",
        printSent = "Отправлено на принтер",
        printFailed = "Принтер не принял задание",
        save = "Сохранить в файл",
        saved = "Сохранено",
        zoomIn = "Крупнее",
        zoomOut = "Мельче",
        fit = "По ширине"
    ),
    status = StatusStrings(
        delivered = "Доставлен",
        resent = "Досланный",
        refused = "Отклонён",
        internal = "Внутренний",
        queued = "В очереди"
    ),
    enums = EnumStrings(
        vatNone = "Без НДС",
        vat0 = "НДС 0%",
        vat5 = "НДС 5%",
        vat10 = "НДС 10%",
        vat16 = "НДС 16%",
        paymentCash = "Наличные",
        paymentCard = "Карта",
        paymentElectronic = "Электронные",
        paymentMobile = "Мобильный платёж",
        paymentCredit = "В кредит",
        paymentTare = "Тарой",
        domainTrading = "Торговля",
        domainServices = "Услуги",
        domainHotels = "Гостиницы",
        domainGasOil = "Нефтепродукты",
        domainTaxi = "Такси",
        domainParking = "Стоянка",
        docCheck = "Чек",
        docShiftOpen = "Открытие смены",
        docShiftClose = "Закрытие смены",
        docCashIn = "Внесение",
        docCashOut = "Изъятие",
        docReportX = "X-отчёт",
        stateActive = "В работе",
        stateIdle = "Готова к работе",
        stateBlocked = "Заблокирована",
        stateProgramming = "Программирование",
        stateRegistration = "Регистрация"
    )
)
