package kz.mybrain.superkassa.desktop.ui.strings

/** English interface text. */
internal val EnglishStrings = AppStrings(
    common = CommonStrings(
        refresh = "Refresh",
        hide = "Hide",
        print = "Print",
        amount = "Amount",
        pin = "PIN",
        loading = "Loading…",
        nodeOnline = "Node online",
        nodeOffline = "Node unreachable",
        nodeUnavailable = "Register node is unreachable",
        nodeNoAnswer = "No answer received — the document may have gone through, check the journal; a repeat will not duplicate it",
        refusalCode = "Refusal code",
        deliveredToOfd = "delivered to the BFD",
        queuedNoLink = "no link — queued",
        deliveryState = "delivery state",
        collapse = "Collapse",
        explain = "Explanation",
        expand = "Expand",
        retry = "Try again",
        nothingToPick = "Nothing to choose from"
    ),
    login = LoginStrings(
        title = "Sign in to the register",
        search = "Search: number, name, company",
        noKkmsTitle = "No registers on this node",
        noKkms = "The node returned no registers. Add one in settings or check the connection.",
        yourKkm = "Your register",
        pick = "Choose",
        picked = "Chosen",
        enter = "Sign in",
        reload = "Reload list",
        noKkmChosen = "No register chosen",
        pickHint = "Choose a register from the list",
        factory = "Serial",
        registrationNumber = "Reg. no."
    ),
    shell = ShellStrings(
        noKkm = "No register chosen",
        autonomous = "Autonomous mode",
        blocked = "Blocked",
        changeCashier = "Change cashier"
    ),
    sections = SectionStrings(
        dashboard = "Overview",
        sale = "Sale",
        returns = "Refund",
        cash = "Cash",
        history = "History",
        queue = "Queue",
        users = "Cashiers",
        settings = "Settings",
        register = "New register",
        cabinet = "BFD cabinet"
    ),
    dashboard = DashboardStrings(
        state = "State",
        shift = "Shift",
        shiftOpenNo = "No. %s open",
        shiftClosed = "Closed",
        cashInDrawer = "Cash in drawer",
        documentsInShift = "Documents in shift",
        shiftDocuments = "Shift documents",
        refused = "Refused by the BFD",
        refusedHint = "The BFD did not accept these documents: they are not fiscal, they are outside the shift " +
            "counters and they have no printed form. The refusal code and the cashier are for support.",
        openShift = "Open shift",
        xReport = "X report",
        closeShift = "Close shift",
        closeShiftAsk = "Close the shift and take the Z report?",
        closeShiftExplain = "Documents in the shift: %s, %s in the drawer. The Z report goes to BFD and cannot be undone.",
        closeShiftCashout = "The remaining cash is withdrawn together with the report.",
        closeShiftKeepsCash = "The remaining cash stays in the drawer and carries over to the next shift.",
        openShiftHint = "The shift is closed — open it to issue receipts",
        openShiftAdmin = "Only an administrator opens the shift — call them to start the day.",
        shiftOpened = "Shift opened",
        shiftClosedDone = "Shift closed, Z report sent",
        xReportDone = "X report produced",
        printForm = "Print form",
        shiftUnknown = "Unknown",
        shiftEmpty = "No documents yet",
        shiftEmptyHint = "The shift is open: the first receipt shows up here right after it goes through.",
        shiftUnknownHint = "The node did not report the shift state — check the link to it in settings.",
        documentNo = "No."

    ),
    autonomous = AutonomousStrings(
        title = "Autonomous mode",
        explain = "There is no link to the BFD. Receipts are issued with an autonomous sign " +
            "and go to the BFD by themselves once the link is back. You can keep working.",
        waiting = "Waiting to be sent",
        checkLink = "Check the link",
        sendQueued = "Send what piled up",
        sendQueuedRules = "Only an admin can flush the queue: the shift must be closed and the register in programming mode.",
        linkBack = "The link to the BFD is back"
    ),
    sale = SaleStrings(
        receipt = "Receipt",
        sale = "Sale",
        purchase = "Purchase",
        issueSale = "Issue receipt",
        issuePurchase = "Issue purchase",
        issuing = "Issuing…",
        name = "Name",
        price = "Price",
        quantity = "Quantity",
        measureUnit = "Unit of measure",
        vat = "VAT",
        discount = "Discount",
        storno = "Storno",
        stornoUndo = "Undo storno",
        add = "Add",
        remove = "Remove",
        clearBasket = "Clear basket",
        receiptDiscount = "Receipt discount",
        receiptMarkup = "Receipt markup",
        discountOrMarkup = "Receipt discount and markup — one or the other",
        customerBin = "Customer IIN/BIN",
        taken = "Tendered",
        total = "Total",
        domainHint = "Fill in the details of the chosen industry — the BFD rejects the receipt without them.",
        barcode = "Barcode",
        barcodeSearch = "Search by barcode",
        barcodeSearching = "Searching…",
        barcodeFind = "Find",
        barcodeMissing = "No such barcode in the catalogue — add the item by hand.",
        domainKind = "Industry",
        accountNumber = "Account number",
        cardNumber = "Card number",
        carNumber = "Car number",
        fee = "Fare",
        byOrder = "By order",
        parkingHours = "Parking hours",
        payment = "Payment type",
        delivered = "receipt issued and delivered to the BFD",
        queued = "receipt issued, no connection — queued",
        deliveryState = "delivery state"
    ),
    returns = ReturnStrings(
        title = "Refund",
        empty = "The current shift has no receipt to refund against.",
        receiptNo = "Receipt No.",
        refundFor = "Refund for receipt No.",
        saleReturn = "Sale refund",
        giveBack = "Give back to customer",
        purchaseReturn = "Purchase refund",
        takeBack = "Take back",
        done = "issued, state"
    ),
    cash = CashStrings(
        title = "Cash in the register",
        inDrawer = "In drawer",
        deposit = "Deposit",
        withdraw = "Withdraw",
        deposited = "Deposited",
        withdrawn = "Withdrawn"
    ),
    history = HistoryStrings(
        title = "Last 24 hours",
        load = "Load",
        loading = "Loading…"
    ),
    queue = QueueStrings(
        title = "Delivery queue",
        empty = "Nothing is waiting — everything reached the BFD.",
        waiting = "Waiting to be sent",
        attempts = "Attempts",
        retryFailed = "Retry failed",
        retryDone = "Failed tasks queued for another attempt"
    ),
    users = UserStrings(
        title = "Cashiers and PINs",
        name = "Name",
        create = "Add",
        created = "added",
        forbiddenPin = "The node will not accept this PIN: default PINs are forbidden.",
        newPin = "New PIN",
        change = "Change",
        changed = "PIN changed",
        delete = "Delete",
        deleted = "deleted",
        role = "Role",
        admin = "Administrator",
        cashier = "Cashier"
    ),
    settings = englishSettings,
    preview = englishPreview,
    status = englishStatus,
    enums = englishEnums
)
