package kz.mybrain.superkassa.desktop.ui.strings

/** Қазақ тіліндегі интерфейс мәтіні. */
internal val KazakhStrings = AppStrings(
    common = CommonStrings(
        refresh = "Жаңарту",
        hide = "Жасыру",
        print = "Басып шығару",
        amount = "Сома",
        pin = "ПИН",
        loading = "Оқылуда…",
        nodeOnline = "Түйін байланыста",
        nodeOffline = "Түйін қолжетімсіз",
        nodeUnavailable = "Касса түйіні қолжетімсіз",
        refusalCode = "Бас тарту коды",
        deliveredToOfd = "ОФД-ға жеткізілді",
        queuedNoLink = "байланыс жоқ — кезекке қойылды",
        deliveryState = "жеткізу күйі",
        collapse = "Жию",
        explain = "Түсіндірме",
        expand = "Жаю",
        retry = "Қайталау"
    ),
    login = LoginStrings(
        title = "Кассаға кіру",
        search = "Іздеу: нөмір, атауы, ұйым",
        noKkms = "Түйін бірде-бір касса бермеді. Баптауларда касса тіркеңіз немесе байланысты тексеріңіз.",
        yourKkm = "Сіздің кассаңыз",
        pick = "Таңдау",
        picked = "Таңдалды",
        enter = "Кіру",
        reload = "Тізімді жаңарту",
        noKkmChosen = "Касса таңдалмады",
        pickHint = "Тізімнен кассаны таңдаңыз",
        factory = "Зауыттық",
        registrationNumber = "Тіркеу нөмірі"
    ),
    shell = ShellStrings(
        noKkm = "Касса таңдалмады",
        autonomous = "Дербес режим",
        blocked = "Бұғатталған",
        changeCashier = "Кассирді ауыстыру"
    ),
    sections = SectionStrings(
        dashboard = "Басты бет",
        sale = "Сату",
        returns = "Қайтару",
        cash = "Ақша",
        history = "Тарих",
        queue = "Кезек",
        users = "Кассирлер",
        settings = "Баптаулар",
        register = "Жаңа касса",
        cabinet = "ОФД кабинеті"
    ),
    dashboard = DashboardStrings(
        state = "Күйі",
        shift = "Ауысым",
        shiftOpenNo = "№ %s ашық",
        shiftClosed = "Жабық",
        cashInDrawer = "Кассадағы қолма-қол ақша",
        documentsInShift = "Ауысымдағы құжаттар",
        shiftDocuments = "Ауысым құжаттары",
        refused = "ОФД қабылдамады",
        refusedHint = "Бұл құжаттарды ОФД қабылдамады: олар фискалдық болмады, ауысым есептеуішіне кірмеді " +
            "және баспа түрі жоқ. Бас тарту коды мен кассир қызмет көрсетуге қажет.",
        openShift = "Ауысымды ашу",
        xReport = "X-есеп",
        closeShift = "Ауысымды жабу",
        openShiftHint = "Ауысым жабық — чек басу үшін ауысымды ашыңыз",
        openShiftAdmin = "Ауысымды әкімші ашады — күнді бастау үшін оны шақырыңыз.",
        shiftOpened = "Ауысым ашылды",
        shiftClosedDone = "Ауысым жабылды, Z-есеп жіберілді",
        xReportDone = "X-есеп жасалды",
        printForm = "Басып шығару пішіні",
        shiftUnknown = "Белгісіз",
        blockedNoActions = "Касса бұғатталған — түйін ауысым әрекеттерін қабылдамайды. Есептен шығарылған кассаға оқу қалады: журнал, ауысымдар және есептер."

    ),
    autonomous = AutonomousStrings(
        title = "Дербес режим",
        explain = "ОФД-мен байланыс жоқ. Чектер басылып, дербес белгі алады, " +
            "ал байланыс пайда болған бойда ОФД-ға өздері жіберіледі. Жұмысты жалғастыруға болады.",
        waiting = "Жіберуді күтуде",
        checkLink = "Байланысты тексеру",
        sendQueued = "Жиналғанды жіберу",
        sendQueuedRules = "Жинақталғанды әкімші жібереді: ауысым жабық болуы және касса бағдарламалау режимінде болуы керек.",
        linkBack = "ОФД-мен байланыс қалпына келді"
    ),
    sale = SaleStrings(
        receipt = "Чек",
        sale = "Сату",
        purchase = "Сатып алу",
        issueSale = "Чекті басу",
        issuePurchase = "Сатып алуды ресімдеу",
        issuing = "Ресімделуде…",
        name = "Атауы",
        price = "Бағасы",
        quantity = "Саны",
        measureUnit = "Өлшем бірлігі",
        vat = "ҚҚС",
        discount = "Жеңілдік",
        storno = "Сторно",
        stornoUndo = "Сторноны алып тастау",
        add = "Қосу",
        remove = "Алып тастау",
        clearBasket = "Себетті тазалау",
        receiptDiscount = "Чекке жеңілдік",
        receiptMarkup = "Чекке үстеме",
        discountOrMarkup = "Чекке жеңілдік пен үстеме — біреуі ғана",
        customerBin = "Сатып алушының ЖСН/БСН",
        taken = "Қабылданды",
        total = "Барлығы",
        domainHint = "Таңдалған сала деректемелерін толтырыңыз — оларсыз ОФД чекті қабылдамайды.",
        barcode = "Штрих-код",
        barcodeSearch = "Штрих-код бойынша іздеу",
        barcodeSearching = "Ізделуде…",
        barcodeFind = "Табу",
        barcodeMissing = "Анықтамалықта мұндай штрих-код жоқ — позицияны қолмен қосыңыз.",
        domainKind = "Сала түрі",
        accountNumber = "Шот нөмірі",
        cardNumber = "Карта нөмірі",
        carNumber = "Көлік нөмірі",
        fee = "Тариф",
        byOrder = "Тапсырыс бойынша",
        parkingHours = "Тұрақ сағаттары",
        payment = "Төлем түрі",
        delivered = "чек басылды және ОФД-ға жеткізілді",
        queued = "чек басылды, байланыс жоқ — кезекке қойылды",
        deliveryState = "жеткізу күйі"
    ),
    returns = ReturnStrings(
        title = "Қайтару",
        empty = "Ағымдағы ауысымда қайтаруға негіз болатын чек жоқ.",
        receiptNo = "Чек №",
        refundFor = "№ чек бойынша қайтару",
        saleReturn = "Сатуды қайтару",
        giveBack = "Сатып алушыға қайтару",
        purchaseReturn = "Сатып алуды қайтару",
        takeBack = "Кері қабылдау",
        done = "ресімделді, күйі"
    ),
    cash = CashStrings(
        title = "Кассадағы ақша",
        inDrawer = "Жәшікте",
        deposit = "Салу",
        withdraw = "Алу",
        deposited = "Салынды",
        withdrawn = "Алынды"
    ),
    history = HistoryStrings(
        title = "Тәулік тарихы",
        load = "Жүктеу",
        loading = "Оқылуда…"
    ),
    queue = QueueStrings(
        title = "Жіберу кезегі",
        empty = "Күтіп тұрған құжат жоқ — бәрі ОФД-ға жеткізілді.",
        waiting = "Жіберуді күтуде",
        attempts = "Әрекеттер",
        retryFailed = "Сәтсіздерді қайталау",
        retryDone = "Сәтсіз тапсырмалар қайталауға қойылды"
    ),
    users = UserStrings(
        title = "Кассирлер мен пиндер",
        name = "Аты",
        create = "Тіркеу",
        created = "тіркелді",
        forbiddenPin = "Мұндай пинді түйін қабылдамайды: стандартты пиндерге тыйым салынған.",
        newPin = "Жаңа пин",
        change = "Ауыстыру",
        changed = "Пин ауыстырылды",
        delete = "Жою",
        deleted = "жойылды",
        role = "Рөлі",
        admin = "Әкімші",
        cashier = "Кассир"
    ),
    settings = kazakhSettings,
    preview = kazakhPreview,
    status = kazakhStatus,
    enums = kazakhEnums
)
