package kz.mybrain.superkassa.desktop.ui.strings

/** English interface text. */
internal val EnglishStrings = AppStrings(
    common = CommonStrings(
        refresh = "Refresh",
        hide = "Hide",
        print = "Print",
        amount = "Amount",
        pin = "PIN",
        loading = "Loading…",
        nodeOnline = "Node online",
        nodeOffline = "Node unreachable",
        nodeUnavailable = "Register node is unreachable",
        refusalCode = "Refusal code",
        deliveredToOfd = "delivered to the OFD",
        queuedNoLink = "no link — queued",
        deliveryState = "delivery state",
        collapse = "Collapse",
        explain = "Explanation",
        expand = "Expand"
    ),
    login = LoginStrings(
        title = "Sign in to the register",
        search = "Search: number, name, company",
        noKkms = "The node returned no registers. Add one in settings or check the connection.",
        yourKkm = "Your register",
        pick = "Choose",
        picked = "Chosen",
        enter = "Sign in",
        reload = "Reload list",
        noKkmChosen = "No register chosen",
        pickHint = "Choose a register from the list",
        factory = "Serial"
    ),
    shell = ShellStrings(
        noKkm = "No register chosen",
        autonomous = "Autonomous mode",
        blocked = "Blocked",
        changeCashier = "Change cashier"
    ),
    sections = SectionStrings(
        dashboard = "Overview",
        sale = "Sale",
        returns = "Refund",
        cash = "Cash",
        history = "History",
        queue = "Queue",
        users = "Cashiers",
        settings = "Settings",
        register = "New register",
        cabinet = "OFD cabinet"
    ),
    dashboard = DashboardStrings(
        state = "State",
        shift = "Shift",
        shiftOpenNo = "No. %s open",
        shiftClosed = "Closed",
        cashInDrawer = "Cash in drawer",
        documentsInShift = "Documents in shift",
        shiftDocuments = "Shift documents",
        refused = "Refused by the OFD",
        refusedHint = "The OFD did not accept these documents: they are not fiscal, they are outside the shift " +
            "counters and they have no printed form. The refusal code and the cashier are for support.",
        openShift = "Open shift",
        xReport = "X report",
        closeShift = "Close shift",
        openShiftHint = "The shift is closed — open it to issue receipts",
        openShiftAdmin = "Only an administrator opens the shift — call them to start the day.",
        shiftOpened = "Shift opened",
        shiftClosedDone = "Shift closed, Z report sent",
        xReportDone = "X report produced",
        printForm = "Print form"

    ),
    autonomous = AutonomousStrings(
        title = "Autonomous mode",
        explain = "There is no link to the OFD. Receipts are issued with an autonomous sign " +
            "and go to the OFD by themselves once the link is back. You can keep working.",
        waiting = "Waiting to be sent",
        checkLink = "Check the link",
        sendQueued = "Send what piled up",
        sendQueuedRules = "Only an admin can flush the queue: the shift must be closed and the register in programming mode.",
        linkBack = "The link to the OFD is back"
    ),
    sale = SaleStrings(
        receipt = "Receipt",
        sale = "Sale",
        purchase = "Purchase",
        issueSale = "Issue receipt",
        issuePurchase = "Issue purchase",
        issuing = "Issuing…",
        name = "Name",
        price = "Price",
        quantity = "Quantity",
        vat = "VAT",
        discount = "Discount",
        storno = "Storno",
        add = "Add",
        remove = "Remove",
        clearBasket = "Clear basket",
        receiptDiscount = "Receipt discount",
        receiptMarkup = "Receipt markup",
        discountOrMarkup = "Receipt discount and markup — one or the other",
        customerBin = "Customer IIN/BIN",
        taken = "Tendered",
        total = "Total",
        domainHint = "Fill in the details of the chosen industry — the OFD rejects the receipt without them.",
        barcode = "Barcode",
        barcodeSearch = "Search by barcode",
        barcodeSearching = "Searching…",
        barcodeFind = "Find",
        barcodeMissing = "No such barcode in the catalogue — add the item by hand.",
        domainKind = "Industry",
        accountNumber = "Account number",
        cardNumber = "Card number",
        carNumber = "Car number",
        fee = "Fare",
        byOrder = "By order",
        parkingHours = "Parking hours",
        payment = "Payment type",
        delivered = "receipt issued and delivered to the OFD",
        queued = "receipt issued, no connection — queued",
        deliveryState = "delivery state"
    ),
    returns = ReturnStrings(
        title = "Refund",
        empty = "The current shift has no receipt to refund against.",
        receiptNo = "Receipt No.",
        refundFor = "Refund for receipt No.",
        saleReturn = "Sale refund",
        giveBack = "Give back to customer",
        purchaseReturn = "Purchase refund",
        takeBack = "Take back",
        done = "issued, state"
    ),
    cash = CashStrings(
        title = "Cash in the register",
        inDrawer = "In drawer",
        deposit = "Deposit",
        withdraw = "Withdraw",
        deposited = "Deposited",
        withdrawn = "Withdrawn"
    ),
    history = HistoryStrings(
        title = "Last 24 hours",
        load = "Load",
        loading = "Loading…"
    ),
    queue = QueueStrings(
        title = "Delivery queue",
        empty = "Nothing is waiting — everything reached the OFD.",
        waiting = "Waiting to be sent",
        attempts = "Attempts",
        retryFailed = "Retry failed",
        retryDone = "Failed tasks queued for another attempt"
    ),
    users = UserStrings(
        title = "Cashiers and PINs",
        name = "Name",
        create = "Add",
        created = "added",
        forbiddenPin = "The node will not accept this PIN: default PINs are forbidden.",
        newPin = "New PIN",
        change = "Change",
        changed = "PIN changed",
        delete = "Delete",
        deleted = "deleted",
        role = "Role",
        admin = "Administrator",
        cashier = "Cashier"
    ),
    settings = SettingStrings(
        title = "Settings",
        currentKkm = "Register in use",
        changeKkm = "Change register",
        registerKkm = "Add a register",
        back = "Back",
        registerKkmHint = "The first register is added before signing in: the node issues a factory number, " +
            "then the register is enrolled in the OFD cabinet and its id and token are entered here.",
        kkmIdentifier = "Register identifier",
        token = "Token",
        adminPin = "Administrator PIN",
        registering = "Adding…",
        register = "Add",
        registered = "Register added, state",
        registerHint = "The administrator PIN is set here and the new register will have no other: " +
            "the node refuses the default one, and it can only be changed from inside. " +
            "Cashiers and their PINs are added later under “Cashiers and PINs”.",
        diagnostics = "Diagnostics",
        ofdLink = "OFD link",
        checkOfdLink = "Check the OFD link",
        ofdAnswers = "OFD answers",
        ofdSilent = "OFD is silent",
        ofdInfo = "OFD information",
        programmingMode = "Programming mode",
        enterProgramming = "Enter programming",
        exitProgramming = "Exit",
        enteredProgramming = "The register entered programming mode",
        exitedProgramming = "The register left programming mode",
        ofd = "OFD",
        environment = "Environment",
        language = "Language",
        appearance = "Appearance",
        ofdToken = "OFD token",
        newToken = "New token",
        saveToken = "Save token",
        tokenSaved = "Token saved",
        tokenHint = "The OFD issues the token. On an \"invalid token\" answer the register stops " +
            "and works again only after a new one is entered.",
        printForm = "Printed receipt",
        programmingRequired = "Register settings change in programming mode.",
        printFormSaved = "Receipt settings saved",
        receiptLanguage = "Receipt language",
        receiptBoth = "Both languages",
        receiptKk = "Қазақша",
        receiptRu = "Русский",
        paperWidth = "Paper width",
        printLayout = "Print layout",
        printer = "Register printer",
        printerHint = "The printer belongs to the register: one computer may hold two, " +
            "each with its own receipt tape. Until one is chosen, jobs go to the system default.",
        printerSystem = "System default",
        printKind = "File kind when saving",
        printCopies = "Copies when printing",
        panelBehaviour = "Till column sections",
        groupAppearance = "Appearance and printing",
        groupService = "Service",
        groupIrreversible = "Irreversible",
        panelBehaviourHint = "What is chosen here is what the cashier sees when the sale screen opens. " +
            "They can still collapse or expand a section with the arrow on the screen itself.",
        panelPositionEntry = "New item",
        panelReceiptDetails = "Receipt details",
        panelMoney = "Payment and total",
        printLayoutHint = "58 and 80 mm tape are for receipt printers; the page is for plain paper " +
            "and for sending to the customer.",
        layoutTape58 = "58 mm tape",
        layoutTape80 = "80 mm tape",
        layoutFullscreen = "Full page",
        printOfdAds = "Print OFD advertising",
        printOfdAdsHint = "The lines arrive with the receipt response and print under the total.",
        receiptLines = "Your own receipt lines",
        receiptLinesHint = "The operator's advertising comes from the OFD; these are the shop's own lines: " +
            "a greeting, return terms, a thank-you. An empty field is not printed.",
        saveReceiptLines = "Save lines",
        lineBeforeHeader = "Above the header",
        lineHeader = "In the header",
        lineAfterHeader = "Below the header",
        lineBeforeItems = "Before the items",
        lineAfterItems = "After the items",
        lineBeforeTotals = "Before the total",
        lineAfterTotals = "After the total",
        lineBeforeQr = "Before the QR code",
        lineFooter = "In the footer",
        appearanceSystem = "Follow system",
        appearanceLight = "Light",
        appearanceDark = "Dark",
        factoryStep = "Step 1. Factory details",
        generateFactory = "Generate",
        factoryNumber = "Serial number",
        manufactureYear = "Year of manufacture",
        factoryHint = "The node issues the serial number by the manufacturer algorithm. " +
            "Take it together with the year to the OFD: they register the machine " +
            "and issue an identifier and a token.",
        ofdStep = "Step 2. Details from the OFD",
        localName = "Local name",
        localNameHint = "The name is visible only at this workplace. " +
            "Register details come from the OFD and are not edited here.",
        save = "Save"
    ),
    preview = PreviewStrings(
        title = "Print form",
        narrower = "Narrower",
        wider = "Wider",
        close = "Close",
        missing = "The node did not return a print form",
        print = "Print",
        printSent = "Sent to the printer",
        printFailed = "The printer refused the job",
        save = "Save to a file",
        saved = "Saved",
        zoomIn = "Zoom in",
        zoomOut = "Zoom out",
        fit = "Fit width"
    ),
    status = StatusStrings(
        delivered = "Delivered",
        resent = "Sent later",
        refused = "Refused",
        internal = "Internal",
        queued = "Queued"
    ),
    enums = EnumStrings(
        vatNone = "No VAT",
        vat0 = "VAT 0%",
        vat5 = "VAT 5%",
        vat10 = "VAT 10%",
        vat16 = "VAT 16%",
        paymentCash = "Cash",
        paymentCard = "Card",
        paymentElectronic = "Electronic",
        paymentMobile = "Mobile payment",
        paymentCredit = "On credit",
        paymentTare = "By tare",
        domainTrading = "Trading",
        domainServices = "Services",
        domainHotels = "Hotels",
        domainGasOil = "Petroleum products",
        domainTaxi = "Taxi",
        domainParking = "Parking",
        docCheck = "Receipt",
        docShiftOpen = "Shift opening",
        docShiftClose = "Shift closing",
        docCashIn = "Deposit",
        docCashOut = "Withdrawal",
        docReportX = "X report",
        stateActive = "In service",
        stateIdle = "Ready",
        stateBlocked = "Blocked",
        stateProgramming = "Programming",
        stateRegistration = "Registration"
    )
)
